const translations = {
    "en": {
        // Documentation
        "docs_title": "Documentation - EEditor",
        "docs_home": "Home",
        "docs_editor": "EEditor",
        "docs_game": "Game",
        "docs_events": "Events",
        "docs_search_placeholder": "Search documentation...",

        // Getting Started
        "docs_getting_started": "Getting Started",
        "docs_getting_started_title": "Getting Started",
        "docs_getting_started_desc": "EEditor is a powerful tool for creating and editing scenarios in the game. In this section, you'll learn the basics of working with the editor.",
        
        "docs_installation_title": "Installation",
        "docs_installation_desc": "To get started with EEditor, you'll need:",
        "docs_requirement_browser": "Modern web browser (Chrome, Firefox, Edge)",
        "docs_requirement_discord": "Discord account for authorization",
        "docs_requirement_knowledge": "Basic knowledge of game mechanics",
        "docs_requirement_editor": "EEditor installed on your computer",
        "docs_requirement_game": "Game installed on your computer",
        "docs_requirement_discord_server": "Discord server with the game",

        // Interface
        "docs_interface": "Interface",
        "docs_interface_title": "Interface",
        "docs_interface_desc": "The EEditor interface is divided into several main sections:",
        "docs_interface_toolbar": "Top toolbar with main tools",
        "docs_interface_sidebar": "Side navigation panel",
        "docs_interface_workspace": "Editing workspace",
        "docs_interface_preview": "Preview panel",

        // Countries
        "docs_countries": "Countries",
        "docs_countries_title": "Countries",
        "docs_countries_desc": "This section describes working with countries in the editor:",
        "docs_countries_create": "Creating new countries",
        "docs_countries_edit": "Editing existing countries",
        "docs_countries_relations": "Setting up relations between countries",
        "docs_countries_territories": "Managing territories",

        // Events
        "docs_events_title": "Events",
        "docs_events_desc": "Events are a key element of scenarios, allowing you to create interesting game situations:",
        "docs_event_creation": "Creating Events",
        "docs_event_creation_title": "Creating Events",
        "docs_event_creation_desc": "The process of creating a new event includes:",
        "docs_event_creation_params": "Defining basic parameters",
        "docs_event_creation_description": "Writing descriptions",
        "docs_event_creation_conditions": "Setting up conditions",
        "docs_event_creation_choices": "Adding choice options",

        // Event Conditions
        "docs_event_conditions": "Conditions",
        "docs_event_conditions_title": "Conditions",
        "docs_event_conditions_desc": "Types of conditions for events:",
        "docs_event_conditions_time": "Time conditions",
        "docs_event_conditions_country": "Country conditions",
        "docs_event_conditions_diplomacy": "Diplomatic conditions",
        "docs_event_conditions_economy": "Economic conditions",

        // Event Effects
        "docs_event_effects": "Effects",
        "docs_event_effects_title": "Effects",
        "docs_event_effects_desc": "Possible event effects:",
        "docs_event_effects_country": "Changing country parameters",
        "docs_event_effects_diplomacy": "Diplomatic changes",
        "docs_event_effects_economy": "Economic effects",
        "docs_event_effects_military": "Military consequences",

        // Event Chains

        // Reforms
        "docs_reforms": "Reforms",
        "docs_reforms_title": "Reforms",
        "docs_reforms_desc": "Reforms allow changing country characteristics during the game:",
        "docs_reforms_types": "Reform types",
        "docs_reforms_conditions": "Reform conditions",
        "docs_reforms_effects": "Reform effects",
        "docs_reforms_chains": "Creating reform chains",

        // Game
        "docs_gameplay": "Gameplay",
        "docs_gameplay_title": "Gameplay",
        "docs_gameplay_desc": "Main aspects of gameplay:",
        "docs_gameplay_management": "Country management",
        "docs_gameplay_economy": "Economic development",
        "docs_gameplay_military": "Military actions",
        "docs_gameplay_diplomacy": "Diplomatic relations",

        // Mechanics
        "docs_mechanics": "Mechanics",
        "docs_mechanics_title": "Mechanics",
        "docs_mechanics_desc": "Basic game mechanics include:",
        "docs_mechanics_economy": "Economic system",
        "docs_mechanics_military": "Military system",
        "docs_mechanics_research": "Research system",
        "docs_mechanics_politics": "Political system",

        // Diplomacy
        "docs_diplomacy": "Diplomacy",
        "docs_diplomacy_title": "Diplomacy",
        "docs_diplomacy_desc": "The diplomatic system allows:",
        "docs_diplomacy_alliances": "Forming alliances",
        "docs_diplomacy_wars": "Declaring wars",
        "docs_diplomacy_trade": "Conducting trade",
        "docs_diplomacy_coalitions": "Creating coalitions",

        // Economy
        "docs_economy": "Economy",
        "docs_economy_title": "Economy",
        "docs_economy_desc": "The economic system includes:",
        "docs_economy_resources": "Resource management",
        "docs_economy_trade": "Trade relations",
        "docs_economy_production": "Production development",
        "docs_economy_finance": "Financial system",

        // Account menu
        "guest": "Guest",
        "login": "Login with Discord",
        "register": "Register",
        "settings": "Settings",
        "logout": "Logout",
        "discord": "Discord Server",
        "stable_version": "Stable Version",

        // Main page
        "editor": "Editor",
        "countries": "Countries",
        "events": "Events",
        "save": "Save",
        "drag_file_here": "Drag file here or",
        "choose_file": "Choose file",
        "file_preview": "File preview",
        "changes_not_saved": "Changes not saved",

        // Settings form
        "title": "Title",
        "id": "ID",
        "last_turn": "Last Turn",
        "year": "Year",
        "month": "Month",
        "play_after_last_turn": "Play After Last Turn",
        "technology_lvl": "Technology Level",
        "technologies_are_opened": "All Technologies Opened",
        "resources_spawn": "Resources Spawn",
        "difficulty": "Difficulty",
        "bots_behavior": "Bots Behavior",
        "no_initial_diplomacy": "No Initial Diplomacy",
        "water_color": "Water Color",
        "no_nuclear_weapon": "No Nuclear Weapon",
        "sandbox": "Sandbox",
        "turn": "Turn",
        "player_land": "Player Country",
        "fog_of_war": "Fog of War",
        "map_hash": "Map Hash",
        "num_of_provinces": "Number of Provinces",
        "min_game_version": "Minimum Game Version",

        // Dropdown values
        "easy": "Easy",
        "standard": "Standard",
        "hard": "Hard",
        "impossible": "Impossible",
        "peaceful": "Peaceful",
        "aggressive": "Aggressive",
        "low": "Low",
        "few": "Few",
        "enabled": "Yes",
        "disabled": "No",

        // Countries page
        "countries_title": "Countries",
        "remove_invalid_owners": "Remove Invalid Owners",
        "add_country": "Add Country",
        "color": "Color",
        "name": "Name",
        "system_name": "System Name",
        "provinces_count": "Provinces Count",
        "capital": "Capital",
        "capital_name": "Capital Name",
        "capital_id": "Capital ID",
        "defeated": "Defeated",
        "political_system": "Political System",
        "democracy": "Democracy",
        "monarchy": "Monarchy",
        "communism": "Communism",
        "fascism": "Fascism",
        "trade_republic": "Trade Republic",
        "allies": "Allies",
        "enemies": "Enemies",
        "independence_guarantees": "Independence Guarantees",
        "guaranteed_by": "Guaranteed By",
        "pacts": "Pacts",
        "sanctions": "Sanctions",
        "vassals": "Vassals",
        "color_r": "R",
        "color_g": "G",
        "color_b": "B",

        // Country edit
        "edit_country": "Edit country",
        "reforms": "Reforms",
        "copy": "Copy",
        "delete": "Delete",
        "add_country_button": "Add country",
        "add": "Add",
        "choose_country": "Choose country",
        "choose_country...": "Choose country...",
        "turn:": "Turn:",

        // Events page
        "events_title": "Events",
        "add_event": "Add event",
        "event_id": "ID",
        "event_group": "Group",
        "event_name": "Name",
        "event_title": "Title",

        // Event edit
        "edit_event": "Edit event",
        "event_image": "Event Image:",
        "event_icon": "Event Icon:",
        "event_group_name": "Group",
        "event_unique_name": "System name",
        "event_hide_later": "Hide later",
        "event_delete_turns": "Delete after (turns)",
        "event_description": "Event description",
        "general_requirements": "General requirements",
        "answer_1": "Answer 1",
        "answer_2": "Answer 2",
        "answer_3": "Answer 3",
        "answer_text": "Answer text",
        "result_description": "Result description",
        "auto_select": "Auto-select if ignored",
        "enable_answer": "Enable answer",
        "requirements": "Requirements",
        "bonuses": "Bonuses",
        "common_requirements": "Common requirements",

        "save": "Save",
        "cancel": "Cancel",
        "add": "Add",

        // Requirements editor
        "requirements_editor": "Requirements Editor",
        "bonus_editor": "Bonus Editor",
        "type": "Type",
        "subtype": "Subtype",
        "action": "Action",
        "value": "Value",
        "enter_number": "Enter number",
        "enter_percent": "Enter percent",
        "enter_value": "Enter value",
        "enter_building_name": "Enter building name",
        "enter_institution_name": "Enter institution name",

        // Requirement types
        "defense": "Change defense",
        "attack": "Change attack",
        "building_cost": "Change building cost",
        "discontent": "Change discontent",
        "population_income": "Change population income",
        "add_random_culture_population": "Add population",
        "prestige": "Change prestige",
        "science": "Change science",
        "money": "Change money",
        "add_oil": "Add oil",
        "add_cruiser": "Add cruiser",
        "add_battleship": "Add battleship",
        "add_tank": "Add tank",
        "add_shock_infantry": "Add shock infantry",
        "add_infantry": "Add infantry",
        "army_losses": "Army losses",
        "relation_ideology_change": "Change ideology relations",
        "relation_change": "Change relations",
        "diplomacy_lift_sanctions": "Lift sanctions",
        "diplomacy_sanctions": "Impose sanctions",
        "diplomacy_pact": "Sign pact",
        "diplomacy_alliance": "Form alliance",
        "diplomacy_peace": "Make peace",
        "diplomacy_war": "Declare war",
        "resurrect_country": "Resurrect country",
        "annex_country": "Annex country",

        // Reforms page
        "reforms_title": "Reforms",
        "add_reform": "Add reform",
        "paste": "Paste",
        "required_ideology": "Required ideology",
        "provinces_amount": "Provinces amount",
        "actions": "Actions",

        // Reform edit
        "edit_reform": "Edit reform",
        "back": "Back",
        "copy_to_buffer": "Copy to buffer",
        "load_for_sync": "Load for sync",
        "new_reform": "New reform",

        // Common
        "yes": "Yes",
        "no": "No",
        "edit": "Edit",
        "select_country": "Select country",
        "select_country_placeholder": "Select country...",
        "turn_number": "Turn:",

        // Modal windows
        "new_country": "New Country",
        "create": "Create",
        "fill_all_fields": "Please fill in all fields",
        "country_exists": "Country with this ID already exists",
        "relation_params": "Relation Parameters",
        "relation_turn": "Start Turn",
        "relation_duration": "Duration",
        "relation_initiator": "Initiator",
        "relation_turn_short": "Turn",
        "relation_duration_short": "Duration",
        "relation_initiator_short": "Initiator",

        // Country names
        "country_civilization_13": "Great Britain",
        "country_civilization_21": "France",
        "country_civilization_22": "Russian Empire",
        "country_undeveloped_land": "Undeveloped Land",

        // File upload section
        "drag_file_here_or": "Drag file here or",
        "choose_file": "Choose file",
        "file_preview": "File preview",
        "event_id": "ID",
        "event_group": "Group",
        "event_unique_name": "System name",
        "event_title": "Title",
        "event_hide_later": "Hide later",
        "event_delete_turns": "Delete after (turns)",
        "event_description": "Event description",
        "answer_text": "Answer text",
        "result_description": "Result description",
        "auto_select_if_ignored": "Auto-select if ignored",
        "reforms_of": "Reforms of",
        "copy_suffix": "copy",
        "function_in_development": "This function is under development",
        "many": "Many",

        // Event images and icons
        "image_preview": "Image preview",
        "icon_preview": "Icon preview",
        
        // Main page settings
        "file_parse_error": "File parse error",
        "file_access_error": "File access error",
        "file_saved": "File saved",
        "file_downloaded": "File downloaded",
        "file_update_error": "File update error",
        "water_color_update_error": "Water color update error",

        // Reform colors
        "random_color": "R",

        // Answers
        "answer_1_title": "Answer 1",
        "answer_2_title": "Answer 2",
        "answer_3_title": "Answer 3",

        // Account dropdown
        "profile": "Profile",
        "logout": "Logout",

        // Requirement types
        "year": "Year",
        "month": "Month",
        "turn": "Turn",
        "land_id": "Country ID",
        "land_name": "Country name",
        "near_water": "Near water",
        "has_pact": "Has pact",
        "has_sanctions": "Has sanctions",
        "has_war": "Has war",
        "enemy_near_capital": "Enemy near capital",
        "lost_capital": "Lost capital",
        "is_defeated": "Is defeated",
        "land_power": "Country power",
        "independent_land": "Independent country",
        "no_enemy": "No enemy",
        "random_value": "Random value",
        "count_of_tasks": "Count of tasks",
        "tax": "Tax",
        "building_exists": "Building exists",
        "political_institution": "Political institution",

        // Actions
        "more": "More",
        "equal": "Equal",
        "not_equal": "Not equal",
        "less": "Less",

        // Filters
        "filter": "Filter",
        "filter_equals": "Equals",
        "filter_not_equals": "Not equals",
        "filter_greater": "Greater than",
        "filter_less": "Less than",
        "filter_greater_equals": "Greater than or equal",
        "filter_less_equals": "Less than or equal",
        "filter_contains": "Contains",
        "filter_color_value": "Select color",
        "filter_number_value": "Enter number",
        "filter_text_value": "Enter text",
        "filter_apply": "Apply",
        "filter_clear": "Clear",
        "filter_clear_all": "Clear all filters",
        "filter_operator": "Operator",
        "filter_value": "Value",
        "duration": "Duration (turns)",

        // New bonuses
        "accelerated_recruit_cost": "Accelerated Recruit Cost",
        "maintaining_army_cost_multiplier": "Army Maintenance Cost Multiplier",
        "population_increase": "Population Growth",
        "recruit_cost": "Recruit Cost",
        "change_country": "Change Country",
        "add_culture_population": "Add Culture Population",
        "cooldown": "Cooldown",
        "enter_percent": "Enter percent",
        "enter_number": "Enter number",
        "filter_groups": "Filter by Groups",

        // Event Structure
        "docs_event_structure_title": "Event Structure",
        "docs_event_structure_desc": "Each event consists of the following elements:",
        "docs_event_basic_params_title": "Basic Parameters",
        "docs_event_param_id": "Event ID - unique identifier in the system",
        "docs_event_param_group": "Event Group - category to which the event belongs",
        "docs_event_param_name": "System Name - technical name of the event",
        "docs_event_param_title": "Title - event name visible to the player",
        "docs_event_param_desc": "Description - detailed situation description",
        "docs_event_param_image": "Event Image - illustration in the event window",
        "docs_event_param_icon": "Event Icon - small image for lists",

        // Event Display Settings
        "docs_event_display_settings_title": "Display Settings",
        "docs_event_setting_hide": "Hide Later - event will disappear after some time",
        "docs_event_setting_delete": "Delete after X turns - automatic event deletion",
        "docs_event_setting_auto": "Auto-selection - action when event is ignored",

        // Event Responses
        "docs_event_responses_title": "Response Options",
        "docs_event_responses_desc": "Each event can have up to three response options:",
        "docs_event_response_text": "Response Text - what player sees in the choice button",
        "docs_event_response_result": "Result Description - what happens when selected",
        "docs_event_response_conditions": "Availability Conditions - when this option is available",
        "docs_event_response_effects": "Effects - what changes occur upon selection",
        "docs_event_response_auto": "Auto-select - whether automatically selected when ignored",

        // Event Time Conditions
        "docs_event_time_conditions_title": "Time Conditions",
        "docs_event_condition_turn": "Specific Turn - event occurs on specified turn",
        "docs_event_condition_year": "Year - event is tied to specific year",
        "docs_event_condition_month": "Month - event occurs in specific month",
        "docs_event_condition_range": "Time Range - event can occur within interval",
        "docs_event_condition_periodic": "Periodicity - event repeats at intervals",

        // Event Country Conditions
        "docs_event_country_conditions_title": "Country Conditions",
        "docs_event_condition_politics": "Political System - required type of government",
        "docs_event_condition_provinces": "Number of Provinces - territory count",
        "docs_event_condition_territories": "Territories - presence of specific provinces",
        "docs_event_condition_economy": "Economy - development level, resources, income",
        "docs_event_condition_military": "Military Power - army size, troop types",
        "docs_event_condition_tech": "Technologies - technology development level",

        // Event Effects
        "docs_event_country_effects_title": "Country Changes",
        "docs_event_effect_params": "Parameters - changing basic indicators",
        "docs_event_effect_territory": "Territories - gaining or losing provinces",
        "docs_event_effect_politics": "Politics - changing political system",
        "docs_event_effect_economy": "Economy - changing economic indicators",
        "docs_event_effect_population": "Population - demographic impact",

        // Event Diplomatic Effects
        "docs_event_diplomatic_effects_title": "Diplomatic Effects",
        "docs_event_effect_war": "Declaring War - starting military actions",
        "docs_event_effect_peace": "Peace Treaties - concluding peace",
        "docs_event_effect_alliance": "Creating Alliances - forming alliances",
        "docs_event_effect_sanctions": "Sanctions - imposing restrictions",
        "docs_event_effect_relations": "Relations - changing diplomatic relations",

        // Event Chains

        // Event Chain Management

        // Console Commands Documentation
        "docs_console": "Console",
        "docs_console_basic_title": "Basic Commands",
        "docs_console_basic_desc": "Basic game control commands:",
        "docs_console_basic_commands": "Show list of all available commands",
        "docs_console_basic_message": "Send private message to player",
        "docs_console_basic_timer": "Reset game timer",

        "docs_console_cheats_title": "Cheats and Debug",
        "docs_console_cheats_desc": "Commands for testing and debugging (not working in multiplayer):",
        "docs_console_cheat_resources": "Get 9999 of all resources",
        "docs_console_cheat_all": "Unlock all technologies and get unlimited values",
        "docs_console_cheat_debug_ai": "Show extended AI information in province menu",
        "docs_console_cheat_debug_names": "Show rectangles for rendering",
        "docs_console_cheat_borders": "Show/hide borders",
        "docs_console_cheat_interface": "Hide interface for 5 seconds (for screenshots)",
        "docs_console_cheat_country": "Change country (select province of desired country)",
        "docs_console_cheat_lost": "Show defeat animation",
        "docs_console_cheat_spawn": "Create army in selected province",
        "docs_console_cheat_results": "Show multiplayer-like results screen",
        "docs_console_cheat_nuclear": "Show nuclear weapon animation (no damage)",
        "docs_console_cheat_nuclear_land": "Show nuclear animation for all provinces of selected country",
        "docs_console_cheat_plane": "Show downed plane animation",
        "docs_console_cheat_fog": "Enable/disable display of other countries' armies and buildings",

        "docs_console_multiplayer_title": "Multiplayer",
        "docs_console_multiplayer_desc": "Commands for multiplayer game management:",
        "docs_console_mp_info": "Get player information",
        "docs_console_mp_history": "Get player history",
        "docs_console_mp_kick": "Kick player",
        "docs_console_mp_ban": "Ban player",
        "docs_console_mp_banid": "Ban player by ID",
        "docs_console_mp_banip": "Ban player by IP",
        "docs_console_mp_unban": "Unban player",
        "docs_console_mp_mute": "Mute player",
        "docs_console_mp_unmute": "Unmute player",

        "docs_console_admin_title": "Admin Commands",
        "docs_console_admin_desc": "Commands for administrators:",
        "docs_console_admin_content": "Show list of available content",
        "docs_console_admin_difficulty": "Set game difficulty",
        "docs_console_admin_enable": "Enable certain actions in game",
        "docs_console_admin_disable": "Disable certain actions in game",
        "docs_console_admin_over": "End current game",
        "docs_console_admin_new": "Start new game with specified scenario",
        "docs_console_admin_delay": "Delay next turn",
        "docs_console_admin_force": "Force start next turn",
        "docs_console_admin_country": "Change player's country",
        "docs_console_admin_message": "Send message to administrator",

        "docs_console_admin_roles_title": "Admin Roles",
        "docs_console_admin_roles_desc": "Description of roles and their capabilities:",
        "docs_console_role_leader": "Leader",
        "docs_console_role_leader_desc": "Role assignment to other players",
        "docs_console_role_admin": "Administrator",
        "docs_console_role_admin_desc": "Game process management",
        "docs_console_role_mod": "Moderator",
        "docs_console_role_mod_desc": "IP ban and mute management",
        "docs_console_role_jmod": "Junior Moderator",
        "docs_console_role_jmod_desc": "Basic moderation commands",

        "docs_console_scenarios_title": "Scenarios and Mods",
        "docs_console_scenarios_desc": "Commands for working with scenarios and modifications:",
        "docs_console_scenario_export": "Export save to scenario.save",
        "docs_console_scenario_import": "Import save from scenario.save",
        "docs_console_scenario_patch": "Adapt scenario to new map version",
        "docs_console_scenario_cinema": "Show map movement animation",
        "docs_console_scenario_check": "Check event requirements",
        "docs_console_scenario_show": "Show event",

                // Настройки
        "settings_title": "Настройки",
        "settings_back": "Назад",
        "settings_in_development": "Эта функция находится в стадии разработки"
    },
    "ru": {
        // Документация
        "docs_title": "Документация - EEditor",
        "docs_home": "Домой",
        "docs_editor": "EEditor",
        "docs_game": "Игра",
        "docs_events": "События",
        "docs_search_placeholder": "Поиск по документации...",

        // Начало работы
        "docs_getting_started": "Начало работы",
        "docs_getting_started_title": "Начало работы",
        "docs_getting_started_desc": "EEditor - это мощный инструмент для создания и редактирования сценариев в игре. У этого раздела вы узнаете основы работы с редактором.",
        
        "docs_installation_title": "Установка",
        "docs_installation_desc": "Для начала работы с EEditor вам потребуется:",
        "docs_requirement_browser": "Современный веб-браузер (Chrome, Firefox, Edge)",
        "docs_requirement_discord": "Аккаунт Discord для авторизации",
        "docs_requirement_knowledge": "Базовые знания о механиках игры",
        "docs_requirement_editor": "EEditor установлен на вашем компьютере",
        "docs_requirement_game": "Игра установлена на вашем компьютере",
        "docs_requirement_discord_server": "Discord сервер с игрой",

        // Интерфейс
        "docs_interface": "Интерфейс",
        "docs_interface_title": "Интерфейс",
        "docs_interface_desc": "Интерфейс EEditor разделен на несколько основных секций:",
        "docs_interface_toolbar": "Верхняя панель с основными инструментами",
        "docs_interface_sidebar": "Боковая панель для навигации",
        "docs_interface_workspace": "Рабочая область редактирования",
        "docs_interface_preview": "Панель предпросмотра",
        "yes": "Да",
        "no": "Нет",

        // Страны
        "docs_countries": "Страны",
        "docs_countries_title": "Страны",
        "docs_countries_desc": "В этом разделе описывается работа со странами в редакторе:",
        "docs_countries_create": "Создание новых стран",
        "docs_countries_edit": "Редактирование существующих",
        "docs_countries_relations": "Настройка отношений между странами",
        "docs_countries_territories": "Управление территориями",

        // События
        "docs_events_title": "События",
        "docs_events_desc": "События - это ключевой элемент сценариев, позволяющий создавать интересные игровые ситуации:",
        "docs_event_creation": "Создание событий",
        "docs_event_creation_title": "Создание событий",
        "docs_event_creation_desc": "Процесс создания нового события включает:",
        "docs_event_creation_params": "Определение базовых параметров",
        "docs_event_creation_description": "Написание описания",
        "docs_event_creation_conditions": "Настройка условий",
        "docs_event_creation_choices": "Добавление вариантов выбора",

        // Условия событий
        "docs_event_conditions": "Условия",
        "docs_event_conditions_title": "Условия",
        "docs_event_conditions_desc": "Типы условий для событий:",
        "docs_event_conditions_time": "Временные условия",
        "docs_event_conditions_country": "Условия страны",
        "docs_event_conditions_diplomacy": "Дипломатические условия",
        "docs_event_conditions_economy": "Экономические условия",

        // Эффекты событий
        "docs_event_effects": "Эффекты",
        "docs_event_effects_title": "Эффекты",
        "docs_event_effects_desc": "Возможные эффекты событий:",
        "docs_event_effects_country": "Изменение параметров страны",
        "docs_event_effects_diplomacy": "Дипломатические изменения",
        "docs_event_effects_economy": "Экономические эффекты",
        "docs_event_effects_military": "Военные последствия",

        // Цепочки событий

        // Реформы
        "docs_reforms": "Реформы",
        "docs_reforms_title": "Реформы",
        "docs_reforms_desc": "Реформы позволяют изменять характеристики стран в процессе игры:",
        "docs_reforms_types": "Типы реформ",
        "docs_reforms_conditions": "Условия проведения",
        "docs_reforms_effects": "Эффекты реформ",
        "docs_reforms_chains": "Создание цепочек реформ",

        // Игра
        "docs_gameplay": "Геймплей",
        "docs_gameplay_title": "Геймплей",
        "docs_gameplay_desc": "Основные аспекты игрового процесса:",
        "docs_gameplay_management": "Управление страной",
        "docs_gameplay_economy": "Развитие экономики",
        "docs_gameplay_military": "Военные действия",
        "docs_gameplay_diplomacy": "Дипломатические отношения",

        // Механики
        "docs_mechanics": "Механики",
        "docs_mechanics_title": "Механики",
        "docs_mechanics_desc": "Базовые игровые механики включают:",
        "docs_mechanics_economy": "Экономическая система",
        "docs_mechanics_military": "Военная система",
        "docs_mechanics_research": "Система исследований",
        "docs_mechanics_politics": "Политическая система",

        // Дипломатия
        "docs_diplomacy": "Дипломатия",
        "docs_diplomacy_title": "Дипломатия",
        "docs_diplomacy_desc": "Дипломатическая система позволяет:",
        "docs_diplomacy_alliances": "Заключать союзы",
        "docs_diplomacy_wars": "Объявлять войны",
        "docs_diplomacy_trade": "Вести торговлю",
        "docs_diplomacy_coalitions": "Создавать коалиции",

        // Экономика
        "docs_economy": "Экономика",
        "docs_economy_title": "Экономика",
        "docs_economy_desc": "Экономическая система включает:",
        "docs_economy_resources": "Управление ресурсами",
        "docs_economy_trade": "Торговые отношения",
        "docs_economy_production": "Розвиток виробництва",
        "docs_economy_finance": "Финансовая система",

        // Меню аккаунта
        "guest": "Гость",
        "login": "Войти через Discord",
        "register": "Регистрация",
        "settings": "Настройки",
        "logout": "Выйти",
        "discord": "Discord сервер",
        "stable_version": "Стабильная версия",

        // Главная страница
        "editor": "Редактор",
        "countries": "Страны",
        "events": "События",
        "save": "Сохранить",
        "drag_file_here": "Перетащите файл сюда или",
        "choose_file": "Выберите файл",
        "file_preview": "Предпросмотр файла",
        "changes_not_saved": "Изменения не сохранены",

        // Форма настроек
        "title": "Заголовок",
        "id": "ID",
        "last_turn": "Последний Ход",
        "year": "Год",
        "month": "Месяц",
        "play_after_last_turn": "Игра После Последнего Хода",
        "technology_lvl": "Уровень Технологий",
        "technologies_are_opened": "Открыты Все Технологии",
        "resources_spawn": "Спаун Ресурсов",
        "difficulty": "Сложность",
        "bots_behavior": "Поведение Ботов",
        "no_initial_diplomacy": "Без Стартовой Дипломатии",
        "water_color": "Цвет Воды",
        "no_nuclear_weapon": "Без Ядерного Оружия",
        "sandbox": "Sandbox",
        "turn": "Ход",
        "player_land": "Страна Игрока",
        "fog_of_war": "Туман Войны",
        "map_hash": "Хэш Карты",
        "num_of_provinces": "Количество Провинций",
        "min_game_version": "Минимальная Версия Игры",

        // Значения выпадающих списков
        "easy": "Легко",
        "standard": "Стандартно",
        "hard": "Сложно",
        "impossible": "Невозможно",
        "peaceful": "Мирные",
        "aggressive": "Агрессивные",
        "low": "Мало",
        "few": "Много",
        "enabled": "Да",
        "disabled": "Нет",

        // Страница стран
        "countries_title": "Страны",
        "remove_invalid_owners": "Удалить пустых владельцев",
        "add_country": "Добавить страну",
        "color": "Цвет",
        "name": "Название",
        "system_name": "Системное название",
        "provinces_count": "Количество провинций",
        "capital": "Столица",
        "capital_name": "Название столицы",
        "capital_id": "ID столицы",
        "defeated": "Побеждена",
        "political_system": "Политический строй",
        "democracy": "Демократия",
        "monarchy": "Монархия",
        "communism": "Коммунизм",
        "fascism": "Фашизм",
        "trade_republic": "Торговая Республика",
        "allies": "Союзники",
        "enemies": "Враги",
        "independence_guarantees": "Гарантии независимости",
        "guaranteed_by": "Гарантии от",
        "pacts": "Пакты",
        "sanctions": "Санкции",
        "vassals": "Вассалы",
        "color_r": "R",
        "color_g": "G",
        "color_b": "B",

        // Country edit
        "edit_country": "Редактирование страны",
        "reforms": "Реформы",
        "copy": "Копировать",
        "delete": "Удалить",
        "add_country_button": "Добавить страну",

        // Страница событий
        "events_title": "События",
        "add_event": "Добавить событие",
        "event_id": "ID",
        "event_group": "Группа",
        "event_name": "Название",
        "event_title": "Заголовок",

        // Редактирование события
        "edit_event": "Редактирование события",
        "event_image": "Картинка события:",
        "event_icon": "Иконка события:",
        "event_group_name": "Группа",
        "event_unique_name": "Системное название",
        "event_hide_later": "Прятать позже",
        "event_delete_turns": "Удалить через (ходов)",
        "event_description": "Описание события",
        "general_requirements": "Общие требования",
        "answer_1": "Ответ 1",
        "answer_2": "Ответ 2",
        "answer_3": "Ответ 3",
        "answer_text": "Текст ответа",
        "result_description": "Описание результату",
        "auto_select": "Выбирать при игнорировании",
        "enable_answer": "Включить ответ",
        "requirements": "Требования",
        "bonuses": "Бонусы",
        "common_requirements": "Общие требования",

        "save": "Сохранить",
        "cancel": "Отмена",
        "add": "Добавить",

        // Редактор требований
        "requirements_editor": "Редактор требований",
        "bonus_editor": "Редактор бонусов",
        "type": "Тип",
        "subtype": "Подтип",
        "action": "Действие",
        "value": "Значение",
        "more": "Больше",
        "equal": "Равно",
        "not_equal": "Не равно",
        "less": "Меньше",

        // Типы требований
        "defense": "Изменить захист",
        "attack": "Изменить атаку",
        "building_cost": "Изменить стоимость строительства",
        "discontent": "Изменить недовольство",
        "population_income": "Изменить доход населения",
        "add_random_culture_population": "Добавить население",
        "prestige": "Изменить престиж",
        "science": "Изменить науку",
        "money": "Изменить деньги",
        "add_oil": "Добавить нефть",
        "add_cruiser": "Добавить крейсер",
        "add_battleship": "Добавить линкор",
        "add_tank": "Добавить танк",
        "add_shock_infantry": "Добавить ударную пяхоту",
        "add_infantry": "Добавить пяхоту",
        "army_losses": "Потери армии",
        "relation_ideology_change": "Изменить отношения с идеологией",
        "relation_change": "Изменить отношения",
        "diplomacy_lift_sanctions": "Снять санкции",
        "diplomacy_sanctions": "Наложить санкции",
        "diplomacy_pact": "Заключить пакт",
        "diplomacy_alliance": "Заключить альянс",
        "diplomacy_peace": "Заключить мир",
        "diplomacy_war": "Объявить войну",
        "resurrect_country": "Восстановить страну",
        "annex_country": "Аннексировать страну",
        "duration": "Длительность (ходов)",

        // Event Structure
        "docs_event_structure_title": "Структура события",
        "docs_event_structure_desc": "Каждое событие состоит из следующих элементов:",
        "docs_event_basic_params_title": "Основные параметры",
        "docs_event_param_id": "ID события - уникальный идентификатор в системе",
        "docs_event_param_group": "Event Group - категория, к которой относится событие",
        "docs_event_param_name": "Системное название - техническое название события",
        "docs_event_param_title": "Title - event name visible to the player",
        "docs_event_param_desc": "Description - detailed situation description",
        "docs_event_param_image": "Event Image - illustration in the event window",
        "docs_event_param_icon": "Event Icon - small image for lists",

        // Event Display Settings
        "docs_event_display_settings_title": "Настройки отображения",
        "docs_event_setting_hide": "Скрывать позже - событие исчезнет через определенное время",
        "docs_event_setting_delete": "Delete after X turns - automatic event deletion",
        "docs_event_setting_auto": "Auto-selection - action when event is ignored",

        // Event Responses
        "docs_event_responses_title": "Варианты ответов",
        "docs_event_responses_desc": "Каждое событие может иметь до трех вариантов ответа:",
        "docs_event_response_text": "Response Text - what player sees in the choice button",
        "docs_event_response_result": "Result Description - what happens when selected",
        "docs_event_response_conditions": "Availability Conditions - when this option is available",
        "docs_event_response_effects": "Effects - what changes occur upon selection",
        "docs_event_response_auto": "Auto-select - whether automatically selected when ignored",

        // Event Time Conditions
        "docs_event_time_conditions_title": "Временные условия",
        "docs_event_condition_turn": "Конкретный ход - событие произойдет в указанный ход",
        "docs_event_condition_year": "Год - событие привязано к определенному году",
        "docs_event_condition_month": "Месяц - событие происходит в конкретный месяц",
        "docs_event_condition_range": "Диапазон времени - событие может произойти в промежутке",
        "docs_event_condition_periodic": "Периодичность - событие повторяется через интервалы",

        // Event Country Conditions
        "docs_event_country_conditions_title": "Условия страны",
        "docs_event_condition_politics": "Политическая система - требуемый тип правления",
        "docs_event_condition_provinces": "Количество провинций - число территорий",
        "docs_event_condition_territories": "Территории - наличие конкретных провинций",
        "docs_event_condition_economy": "Экономика - уровень развития, ресурсы, доходы",
        "docs_event_condition_military": "Военная мощь - размер армии, типы войск",
        "docs_event_condition_tech": "Технологии - уровень развития технологий",

        // Event Effects
        "docs_event_country_effects_title": "Изменения страны",
        "docs_event_effect_params": "Параметры - изменение базовых показателей",
        "docs_event_effect_territory": "Территории - получение или потеря провинций",
        "docs_event_effect_politics": "Политика - смена политической системы",
        "docs_event_effect_economy": "Экономика - изменение экономических показателей",
        "docs_event_effect_population": "Население - влияние на демографию",

        // Event Diplomatic Effects
        "docs_event_diplomatic_effects_title": "Дипломатические эффекты",
        "docs_event_effect_war": "Объявление войны - начало военных действий",
        "docs_event_effect_peace": "Мирные договоры - заключение мира",
        "docs_event_effect_alliance": "Создание союзов - формирование альянсов",
        "docs_event_effect_sanctions": "Санкции - введение ограничений",
        "docs_event_effect_relations": "Отношения - изменение дипломатических отношений",

        // Event Chains

        // Event Chain Management

        // Console Commands Documentation
        "docs_console": "Консоль",
        "docs_console_basic_title": "Базовые команды",
        "docs_console_basic_desc": "Основные команды для управления игрой:",
        "docs_console_basic_commands": "Показать список всех доступных команд",
        "docs_console_basic_message": "Отправить личное сообщение игроку",
        "docs_console_basic_timer": "Сбросить таймер игры",

        "docs_console_cheats_title": "Читы и отладка",
        "docs_console_cheats_desc": "Команды для тестирования и отладки (не работают в мультиплеере):",
        "docs_console_cheat_resources": "Получить 9999 всех ресурсов",
        "docs_console_cheat_all": "Открыть все технологии и получить безлимитные значения",
        "docs_console_cheat_debug_ai": "Показать расширенную информацию о ботах в меню провинции",
        "docs_console_cheat_debug_names": "Показать прямоугольники для отрисовки",
        "docs_console_cheat_borders": "Показать/скрыть границы",
        "docs_console_cheat_interface": "Скрыть интерфейс на 5 секунд (для скриншотов)",
        "docs_console_cheat_country": "Сменить страну (выберите провинцию нужной страны)",
        "docs_console_cheat_lost": "Показать анимацию поражения",
        "docs_console_cheat_spawn": "Создать армию в выбранной провинции",
        "docs_console_cheat_results": "Показать экран результатов как в мультиплеере",
        "docs_console_cheat_nuclear": "Показать анимацию ядерного оружия (без урона)",
        "docs_console_cheat_nuclear_land": "Показать ядерную анимацию для всех провинций выбранной страны",
        "docs_console_cheat_plane": "Показать анимацию сбитого самолета",
        "docs_console_cheat_fog": "Включить/выключить отображение армии и построек других стран",

        "docs_console_multiplayer_title": "Мультиплеер",
        "docs_console_multiplayer_desc": "Команды для управления многопользовательской игрой:",
        "docs_console_mp_info": "Получить информацию об игроке",
        "docs_console_mp_history": "Получить историю игрока",
        "docs_console_mp_kick": "Выгнать игрока",
        "docs_console_mp_ban": "Забанить игрока",
        "docs_console_mp_banid": "Забанить игрока по ID",
        "docs_console_mp_banip": "Забанить игрока по IP",
        "docs_console_mp_unban": "Разбанить игрока",
        "docs_console_mp_mute": "Заглушить игрока",
        "docs_console_mp_unmute": "Снять заглушение с игрока",

        "docs_console_admin_title": "Админские команды",
        "docs_console_admin_desc": "Команды для администраторов:",
        "docs_console_admin_content": "Показать список доступного контента",
        "docs_console_admin_difficulty": "Установить сложность игры",
        "docs_console_admin_enable": "Включить определенные действия в игре",
        "docs_console_admin_disable": "Выключить определенные действия в игре",
        "docs_console_admin_over": "Завершить текущую игру",
        "docs_console_admin_new": "Начать новую игру с указанным сценарием",
        "docs_console_admin_delay": "Отложить следующий ход",
        "docs_console_admin_force": "Принудительно начать следующий ход",
        "docs_console_admin_country": "Изменить страну игрока",
        "docs_console_admin_message": "Отправить сообщение администратору",

        "docs_console_admin_roles_title": "Роли админов",
        "docs_console_admin_roles_desc": "Описание ролей и их возможностей:",
        "docs_console_role_leader": "Лидер",
        "docs_console_role_leader_desc": "Выдача ролей другим игрокам",
        "docs_console_role_admin": "Администратор",
        "docs_console_role_admin_desc": "Управление игровым процессом",
        "docs_console_role_mod": "Модератор",
        "docs_console_role_mod_desc": "Управление банами по IP и мутами",
        "docs_console_role_jmod": "Младший модератор",
        "docs_console_role_jmod_desc": "Базовые команды модерации",

        "docs_console_scenarios_title": "Сценарии и моды",
        "docs_console_scenarios_desc": "Команды для роботи зі сценаріями та модифікаціями:",
        "docs_console_scenario_export": "Экспортувати збереження в scenario.save",
        "docs_console_scenario_import": "Імпортувати збереження з scenario.save",
        "docs_console_scenario_patch": "Адаптувати сценарій до нової версії карти",
        "docs_console_scenario_cinema": "Показати анімацію руху карти",
        "docs_console_scenario_check": "Перевірити вимоги для події",
        "docs_console_scenario_show": "Показати подію",

        // Settings
        "settings_title": "Настройки",
        "settings_back": "Назад",
        "settings_in_development": "Эта функция находится в разработке"
    },
    "uk": {
        // Документація
        "docs_title": "Документація - EEditor",
        "docs_home": "Додому",
        "docs_editor": "EEditor",
        "docs_game": "Гра",
        "docs_events": "Події",
        "docs_search_placeholder": "Пошук по документації...",

        // Початок роботи
        "docs_getting_started": "Початок роботи",
        "docs_getting_started_title": "Початок роботи",
        "docs_getting_started_desc": "EEditor - це потужний інструмент для створення та редагування сценаріїв у грі. У цьому розділі ви дізнаєтесь основи роботи з редактором.",
        
        "docs_installation_title": "Встановлення",
        "docs_installation_desc": "Для початку роботи з EEditor вам потрібно:",
        "docs_requirement_browser": "Сучасний веб-браузер (Chrome, Firefox, Edge)",
        "docs_requirement_discord": "Обліковий запис Discord для авторизації",
        "docs_requirement_knowledge": "Базові знання про механіки гри",
        "docs_requirement_editor": "EEditor встановлений на вашому комп'ютері",
        "docs_requirement_game": "Гра встановлена на вашому комп'ютері",
        "docs_requirement_discord_server": "Discord сервер з грою",

        // Інтерфейс
        "docs_interface": "Інтерфейс",
        "docs_interface_title": "Інтерфейс",
        "docs_interface_desc": "Інтерфейс EEditor розділений на кілька основних секцій:",
        "docs_interface_toolbar": "Верхня панель з основними інструментами",
        "docs_interface_sidebar": "Бічна панель для навігації",
        "docs_interface_workspace": "Робоча область редагування",
        "docs_interface_preview": "Панель попереднього перегляду",

        // Країни
        "docs_countries": "Країни",
        "docs_countries_title": "Країни",
        "docs_countries_desc": "У цьому розділі описується робота з країнами в редакторі:",
        "docs_countries_create": "Створення нових країн",
        "docs_countries_edit": "Редагування існуючих",
        "docs_countries_relations": "Налаштування відносин між країнами",
        "docs_countries_territories": "Управління територіями",

        // Події
        "docs_events_title": "Події",
        "docs_events_desc": "Події - це ключовий елемент сценаріїв, що дозволяє створювати цікаві ігрові ситуації:",
        "docs_event_creation": "Створення подій",
        "docs_event_creation_title": "Створення подій",
        "docs_event_creation_desc": "Процес створення нової події включає:",
        "docs_event_creation_params": "Визначення базових параметрів",
        "docs_event_creation_description": "Написання опису",
        "docs_event_creation_conditions": "Налаштування умов",
        "docs_event_creation_choices": "Додавання варіантів вибору",

        // Умови подій
        "docs_event_conditions": "Умови",
        "docs_event_conditions_title": "Умови",
        "docs_event_conditions_desc": "Типи умов для подій:",
        "docs_event_conditions_time": "Часові умови",
        "docs_event_conditions_country": "Умови країни",
        "docs_event_conditions_diplomacy": "Дипломатичні умови",
        "docs_event_conditions_economy": "Економічні умови",

        // Ефекти подій
        "docs_event_effects": "Ефекти",
        "docs_event_effects_title": "Ефекти",
        "docs_event_effects_desc": "Можливі ефекти подій:",
        "docs_event_effects_country": "Зміна параметрів країни",
        "docs_event_effects_diplomacy": "Дипломатичні зміни",
        "docs_event_effects_economy": "Економічні ефекти",
        "docs_event_effects_military": "Військові наслідки",

        // Ланцюжки подій

        // Реформи
        "docs_reforms": "Реформи",
        "docs_reforms_title": "Реформи",
        "docs_reforms_desc": "Реформи дозволяють змінювати характеристики країн під час гри:",
        "docs_reforms_types": "Типи реформ",
        "docs_reforms_conditions": "Умови проведення",
        "docs_reforms_effects": "Ефекти реформ",
        "docs_reforms_chains": "Створення ланцюжків реформ",

        // Гра
        "docs_gameplay": "Геймплей",
        "docs_gameplay_title": "Геймплей",
        "docs_gameplay_desc": "Основні аспекти ігрового процесу:",
        "docs_gameplay_management": "Управління країною",
        "docs_gameplay_economy": "Розвиток економіки",
        "docs_gameplay_military": "Військові дії",
        "docs_gameplay_diplomacy": "Дипломатичні відносини",

        // Механіки
        "docs_mechanics": "Механіки",
        "docs_mechanics_title": "Механіки",
        "docs_mechanics_desc": "Базові ігрові механіки включають:",
        "docs_mechanics_economy": "Економічна система",
        "docs_mechanics_military": "Військова система",
        "docs_mechanics_research": "Система досліджень",
        "docs_mechanics_politics": "Політична система",

        // Дипломатія
        "docs_diplomacy": "Дипломатія",
        "docs_diplomacy_title": "Дипломатія",
        "docs_diplomacy_desc": "Дипломатична система дозволяє:",
        "docs_diplomacy_alliances": "Укладати союзи",
        "docs_diplomacy_wars": "Оголошувати війни",
        "docs_diplomacy_trade": "Вести торгівлю",
        "docs_diplomacy_coalitions": "Створювати коаліції",

        // Економіка
        "docs_economy": "Економіка",
        "docs_economy_title": "Економіка",
        "docs_economy_desc": "Економічна система включає:",
        "docs_economy_resources": "Управління ресурсами",
        "docs_economy_trade": "Торгові відносини",
        "docs_economy_production": "Розвиток виробництва",
        "docs_economy_finance": "Фінансова система",

        // Меню аккаунта
        "guest": "Гість",
        "login": "Увійти через Discord",
        "register": "Реєстрація",
        "settings": "Налаштування",
        "logout": "Вийти",
        "discord": "Discord сервер",
        "stable_version": "Стабільна версія",

        // Главная страница
        "editor": "Редактор",
        "countries": "Страны",
        "events": "События",
        "save": "Зберегти",
        "drag_file_here": "Перетагніть файл сюди або",
        "choose_file": "Виберіть файл",
        "file_preview": "Попередній перегляд файлу",
        "changes_not_saved": "Зміни не збережені",

        // Форма налаштувань
        "title": "Назва",
        "id": "ID",
        "last_turn": "Останній Хід",
        "year": "Рік",
        "month": "Ай",
        "play_after_last_turn": "Гра Після Останнього Ходу",
        "technology_lvl": "Рівень Технологій",
        "technologies_are_opened": "Відкриті Всі Технології",
        "resources_spawn": "Спаун Ресурсів",
        "difficulty": "Складність",
        "bots_behavior": "Поведінка Ботів",
        "no_initial_diplomacy": "Без пачатковай діпламатії",
        "water_color": "Су түсі",
        "no_nuclear_weapon": "Без ядзерної зброї",
        "sandbox": "Пісочниця",
        "turn": "Ход",
        "player_land": "Країна гравця",
        "fog_of_war": "Туман війни",
        "map_hash": "Хеш карти",
        "min_game_version": "Мінімальна версія гри",

        // Значення випадаючих списків
        "easy": "Легко",
        "standard": "Стандартно",
        "hard": "Складно",
        "impossible": "Неможливо",
        "peaceful": "Мирні",
        "aggressive": "Агресивні",
        "low": "Мало",
        "few": "Багато",
        "enabled": "Так",
        "disabled": "Ні",

        // Страница країн
        "countries_title": "Країни",
        "remove_invalid_owners": "Видалити порожніх власників",
        "add_country": "Додати країну",
        "color": "Колір",
        "name": "Назва",
        "system_name": "Системна назва",
        "provinces_count": "Кількість провінцій",
        "capital": "Столиця",
        "capital_name": "Назва столиці",
        "capital_id": "ID столиці",
        "defeated": "Переможена",
        "political_system": "Політичний устрій",
        "democracy": "Демократія",
        "monarchy": "Монархія",
        "communism": "Коммунизм",
        "fascism": "Фашизм",
        "trade_republic": "Торгівельна Республіка",
        "allies": "Союзники",
        "enemies": "Вороги",
        "independence_guarantees": "Гарантії незалежності",
        "guaranteed_by": "Гарантії від",
        "pacts": "Пакти",
        "sanctions": "Санкції",
        "vassals": "Васалы",
        "color_r": "R",
        "color_g": "G",
        "color_b": "B",

        // Country edit
        "edit_country": "Редагування країни",
        "reforms": "Реформи",
        "copy": "Копіювати",
        "delete": "Видалити",
        "add_country_button": "Додати країну",

        // Страница событий
        "events_title": "События",
        "add_event": "Добавить подію",
        "event_id": "ID",
        "event_group": "Група",
        "event_name": "Назва",
        "event_title": "Заголовок",

        // Редагування події
        "edit_event": "Редагування події",
        "event_image": "Зображення події:",
        "event_icon": "Іконка події:",
        "event_group_name": "Група",
        "event_unique_name": "Системна назва",
        "event_hide_later": "Приховати пізніше",
        "event_delete_turns": "Видалити через (ходів)",
        "event_description": "Опис події",
        "general_requirements": "Загальні вимоги",
        "answer_1": "Відповідь 1",
        "answer_2": "Відповідь 2",
        "answer_3": "Відповідь 3",
        "answer_text": "Текст відповіді",
        "result_description": "Опис результату",
        "auto_select": "Вибирати при ігноруванні",
        "enable_answer": "Увімкнути відповідь",
        "requirements": "Вимоги",
        "bonuses": "Бонуси",
        "common_requirements": "Загальні вимоги",

        "save": "Зберегти",
        "cancel": "Скасувати",
        "add": "Добавить",

        // Редактор вимог
        "requirements_editor": "Редактор вимог",
        "bonus_editor": "Редактор бонусів",
        "type": "Түрі",
        "subtype": "Қосымша түрі",
        "action": "Әрекет",
        "value": "Мән",
        "more": "Көп",
        "equal": "Тең",
        "not_equal": "Тең емес",
        "less": "Аз",

        // Типи вимог
        "defense": "Қорғанысты өзгерту",
        "attack": "Шабуылды өзгерту",
        "building_cost": "Құрылыс құнын өзгерту",
        "discontent": "Наразылықты өзгерту",
        "population_income": "Халық табысын өзгерту",
        "add_random_culture_population": "Халық қосу",
        "prestige": "Беделді өзгерту",
        "science": "Змяніць науку",
        "money": "Змяніць грошы",
        "add_oil": "Мұнай қосу",
        "add_cruiser": "Добавить крейсер",
        "add_battleship": "Добавить линкор",
        "add_tank": "Добавить танк",
        "add_shock_infantry": "Добавить ударну піхоту",
        "add_infantry": "Добавить піхоту",
        "army_losses": "Втрати армії",
        "relation_ideology_change": "Идеологиямен қарым-қатынасты өзгерту",
        "relation_change": "Змяніць адносіны",
        "diplomacy_lift_sanctions": "Зняць санкцыі",
        "diplomacy_sanctions": "Накласці санкцыі",
        "diplomacy_pact": "Укласти пакт",
        "diplomacy_alliance": "Укласти альянс",
        "diplomacy_peace": "Укласти мир",
        "diplomacy_war": "Оголосити війну",
        "resurrect_country": "Відновити країну",
        "annex_country": "Елді қосып алу",
        "duration": "Длительность (ходов)",

        // Event Structure
        "docs_event_structure_title": "Структура события",
        "docs_event_structure_desc": "Каждое событие состоит из следующих элементов:",
        "docs_event_basic_params_title": "Основные параметры",
        "docs_event_param_id": "ID события - уникальный идентификатор в системе",
        "docs_event_param_group": "Event Group - категория, к которой относится событие",
        "docs_event_param_name": "Системное название - техническое название события",
        "docs_event_param_title": "Title - event name visible to the player",
        "docs_event_param_desc": "Description - detailed situation description",
        "docs_event_param_image": "Event Image - illustration in the event window",
        "docs_event_param_icon": "Event Icon - small image for lists",

        // Event Display Settings
        "docs_event_display_settings_title": "Настройки отображения",
        "docs_event_setting_hide": "Скрывать позже - событие исчезнет через определенное время",
        "docs_event_setting_delete": "Delete after X turns - automatic event deletion",
        "docs_event_setting_auto": "Auto-selection - action when event is ignored",

        // Event Responses
        "docs_event_responses_title": "Варианты ответов",
        "docs_event_responses_desc": "Каждое событие может иметь до трех вариантов ответа:",
        "docs_event_response_text": "Response Text - what player sees in the choice button",
        "docs_event_response_result": "Result Description - what happens when selected",
        "docs_event_response_conditions": "Availability Conditions - when this option is available",
        "docs_event_response_effects": "Effects - what changes occur upon selection",
        "docs_event_response_auto": "Auto-select - whether automatically selected when ignored",

        // Event Time Conditions
        "docs_event_time_conditions_title": "Временные условия",
        "docs_event_condition_turn": "Конкретный ход - событие произойдет в указанный ход",
        "docs_event_condition_year": "Год - событие привязано к определенному году",
        "docs_event_condition_month": "Месяц - событие происходит в конкретный месяц",
        "docs_event_condition_range": "Диапазон времени - событие может произойти в промежутке",
        "docs_event_condition_periodic": "Периодичность - событие повторяется через интервалы",

        // Event Country Conditions
        "docs_event_country_conditions_title": "Условия страны",
        "docs_event_condition_politics": "Политическая система - требуемый тип правления",
        "docs_event_condition_provinces": "Количество провинций - число территорий",
        "docs_event_condition_territories": "Территории - наличие конкретных провинций",
        "docs_event_condition_economy": "Экономика - уровень развития, ресурсы, доходы",
        "docs_event_condition_military": "Военная мощь - размер армии, типы войск",
        "docs_event_condition_tech": "Технологии - уровень развития технологий",

        // Event Effects
        "docs_event_country_effects_title": "Изменения страны",
        "docs_event_effect_params": "Параметры - изменение базовых показателей",
        "docs_event_effect_territory": "Территории - получение или потеря провинций",
        "docs_event_effect_politics": "Политика - смена политической системы",
        "docs_event_effect_economy": "Экономика - изменение экономических показателей",
        "docs_event_effect_population": "Население - влияние на демографию",

        // Event Diplomatic Effects
        "docs_event_diplomatic_effects_title": "Дипломатические эффекты",
        "docs_event_effect_war": "Объявление войны - начало военных действий",
        "docs_event_effect_peace": "Мирные договоры - заключение мира",
        "docs_event_effect_alliance": "Создание союзов - формирование альянсов",
        "docs_event_effect_sanctions": "Санкции - введение ограничений",
        "docs_event_effect_relations": "Отношения - изменение дипломатических отношений",

        // Event Chains

        // Event Chain Management

        // Console Commands Documentation
        "docs_console": "Консольні команди",
        "docs_console_basic_title": "Базові команди",
        "docs_console_basic_desc": "Основні команди для керування грою:",
        "docs_console_basic_commands": "Показати список всіх доступних команд",
        "docs_console_basic_message": "Надіслати приватне повідомлення гравцю",
        "docs_console_basic_timer": "Скинути таймер гри",

        "docs_console_cheats_title": "Чіти та налагодження",
        "docs_console_cheats_desc": "Команди для тестування та налагодження (не працюють у мультиплеєрі):",
        "docs_console_cheat_resources": "Отримати 9999 всіх ресурсів",
        "docs_console_cheat_all": "Відкрити всі технології та отримати безлімітні значення",
        "docs_console_cheat_debug_ai": "Показати розширену інформацію про ботів у меню провінції",
        "docs_console_cheat_debug_names": "Показати прямокутники для відмальовки",
        "docs_console_cheat_borders": "Показати/приховати кордони",
        "docs_console_cheat_interface": "Приховати інтерфейс на 5 секунд (для скріншотів)",
        "docs_console_cheat_country": "Змінити країну (виберіть провінцію потрібної країни)",
        "docs_console_cheat_lost": "Показати анімацію поразки",
        "docs_console_cheat_spawn": "Створити армію у вибраній провінції",
        "docs_console_cheat_results": "Показати екран результатів як у мультиплеєрі",
        "docs_console_cheat_nuclear": "Показати анімацію ядерної зброї (без шкоди)",
        "docs_console_cheat_nuclear_land": "Показати ядерну анімацію для всіх провінцій вибраної країни",
        "docs_console_cheat_plane": "Показати анімацію збитого літака",
        "docs_console_cheat_fog": "Увімкнути/вимкнути відображення армії та будівель інших країн",

        "docs_console_multiplayer_title": "Мультиплеєр",
        "docs_console_multiplayer_desc": "Команди для керування багатокористувацькою грою:",
        "docs_console_mp_info": "Отримати інформацію про гравця",
        "docs_console_mp_history": "Отримати історію гравця",
        "docs_console_mp_kick": "Вигнати гравця",
        "docs_console_mp_ban": "Забанити гравця",
        "docs_console_mp_banid": "Забанити гравця за ID",
        "docs_console_mp_banip": "Забанити гравця за IP",
        "docs_console_mp_unban": "Розбанити гравця",
        "docs_console_mp_mute": "Заглушити гравця",
        "docs_console_mp_unmute": "Зняти заглушення з гравця",

        "docs_console_admin_title": "Адмінські команди",
        "docs_console_admin_desc": "Команди для адміністраторів:",
        "docs_console_admin_content": "Показати список доступного контенту",
        "docs_console_admin_difficulty": "Встановити складність гри",
        "docs_console_admin_enable": "Увімкнути певні дії в грі",
        "docs_console_admin_disable": "Вимкнути певні дії в грі",
        "docs_console_admin_over": "Завершити поточну гру",
        "docs_console_admin_new": "Почати нову гру з вказаним сценарієм",
        "docs_console_admin_delay": "Відкласти наступний хід",
        "docs_console_admin_force": "Примусово почати наступний хід",
        "docs_console_admin_country": "Змінити країну гравця",
        "docs_console_admin_message": "Надіслати повідомлення адміністратору",

        "docs_console_admin_roles_title": "Ролі адмінів",
        "docs_console_admin_roles_desc": "Опис ролей та їх можливостей:",
        "docs_console_role_leader": "Лідер",
        "docs_console_role_leader_desc": "Видача ролей іншим гравцям",
        "docs_console_role_admin": "Адміністратор",
        "docs_console_role_admin_desc": "Керування ігровим процесом",
        "docs_console_role_mod": "Модератор",
        "docs_console_role_mod_desc": "Керування банами за IP та заглушеннями",
        "docs_console_role_jmod": "Молодший модератор",
        "docs_console_role_jmod_desc": "Базові команди модерації",

        "docs_console_scenarios_title": "Сценарії та моди",
        "docs_console_scenarios_desc": "Команди для роботи зі сценаріями та модифікаціями:",
        "docs_console_scenario_export": "Експортувати збереження в scenario.save",
        "docs_console_scenario_import": "Імпортувати збереження з scenario.save",
        "docs_console_scenario_patch": "Адаптувати сценарій до нової версії карти",
        "docs_console_scenario_cinema": "Показати анімацію руху карти",
        "docs_console_scenario_check": "Перевірити вимоги для події",
        "docs_console_scenario_show": "Показати подію",

        // Settings
        "settings_title": "Налаштування",
        "settings_back": "Назад",
        "settings_in_development": "Ця функція знаходиться в розробці"
    },
    "be": {
        // Галоўная старонка
        "editor": "Рэдактар",
        "countries": "Краіны",
        "events": "Падзеі",
        "save": "Захаваць",
        "drag_file_here": "Перацягніце файл сюды або",
        "choose_file": "Выберыце файл",
        "file_preview": "Папярэдні прагляд файла",
        "changes_not_saved": "Змены не захаваны",

        // Налады гульні
        "title": "Назва",
        "id": "ID",
        "last_turn": "Апошні ход",
        "year": "Год",
        "month": "Месяц",
        "play_after_last_turn": "Гульня пасля апошняга ходу",
        "technology_lvl": "Узровень тэхналогій",
        "technologies_are_opened": "Адкрыты ўсе тэхналогіі",
        "resources_spawn": "Спаўн рэсурсаў",
        "difficulty": "Складанасць",
        "bots_behavior": "Паводзіны ботаў",
        "no_initial_diplomacy": "Без пачатковай дыпламатыі",
        "water_color": "Цвет Воды",
        "no_nuclear_weapon": "Без ядзернай зброі",
        "sandbox": "Пясочніца",
        "turn": "Ход",
        "player_land": "Краіна гульца",
        "fog_of_war": "Туман вайны",
        "map_hash": "Хэш карты",
        "min_game_version": "Мінімальная версія гульні",

        // Падзеі
        "event_image": "Малюнак падзеі",
        "event_icon": "Значок падзеі",
        "event_group": "Група падзей",
        "event_name": "Назва падзеі",
        "event_title": "Загаловак падзеі",
        "event_description": "Апісанне падзеі",
        "event_hide_later": "Схаваць пазней",
        "event_delete_turns": "Выдаліць праз (хадоў)",
        "answer_text": "Тэкст адказу",
        "result_description": "Апісанне выніку",
        "auto_select_if_ignored": "Выбіраць пры ігнараванні",
        "enable_answer": "Уключыць адказ",

        // Патрабаванні і бонусы
        "requirements_editor": "Рэдактар патрабаванняў",
        "bonus_editor": "Рэдактар бонусаў",
        "type": "Тып",
        "subtype": "Падтып",
        "action": "Дзеянне",
        "value": "Значэнне",
        "more": "Больш",
        "equal": "Роўна",
        "not_equal": "Не роўна",
        "less": "Менш",

        // Тыпы патрабаванняў
        "defense": "Змяніць абарону",
        "attack": "Змяніць атаку",
        "building_cost": "Змяніць кошт будаўніцтва",
        "discontent": "Змяніць незадаволенасць",
        "population_income": "Змяніць даход насельніцтва",
        "add_random_culture_population": "Дадаць насельніцтва",
        "prestige": "Змяніць прэстыж",
        "science": "Змяніць навуку",
        "money": "Змяніць грошы",
        "add_oil": "Дадаць нафту",
        "add_cruiser": "Дадаць крейсер",
        "add_battleship": "Дадаць лінкор",
        "add_tank": "Дадаць танк",
        "add_shock_infantry": "Дадаць ударную пяхоту",
        "add_infantry": "Дадаць пяхоту",
        "army_losses": "Страты войска",
        "relation_ideology_change": "Изменить адносіны з ідэалогіяй",
        "relation_change": "Змяніць адносіны",
        "diplomacy_lift_sanctions": "Зняць санкцыі",
        "diplomacy_sanctions": "Накласці санкцыі",
        "diplomacy_pact": "Заключыць пакт",
        "diplomacy_alliance": "Заключыць альянс",
        "diplomacy_peace": "Заключыць мір",
        "diplomacy_war": "Аб'явіць вайну",
        "resurrect_country": "Восстановиць краіну",
        "annex_country": "Аннексаваць краіну",
        "duration": "Длительность (ходов)"
    },
    "kk": {
        // Басты бет
        "editor": "Редактор",
        "countries": "Елдер",
        "events": "Оқиғалар",
        "save": "Сақтау",
        "drag_file_here": "Файлды осында сүйреңіз немесе",
        "choose_file": "Файлды таңдаңыз",
        "file_preview": "Файлды алдын ала қарау",
        "changes_not_saved": "Өзгерістер сақталмады",

        // Ойын параметрлері
        "title": "Атауы",
        "id": "ID",
        "last_turn": "Соңғы жүріс",
        "year": "Жыл",
        "month": "Ай",
        "play_after_last_turn": "Соңғы жүрістен кейінгі ойын",
        "technology_lvl": "Технология деңгейі",
        "technologies_are_opened": "Барлық технологиялар ашық",
        "resources_spawn": "Ресурстардың пайда болуы",
        "difficulty": "Қиындық",
        "bots_behavior": "Боттардың міneз-құлқы",
        "no_initial_diplomacy": "Бастапқы дипломатиясыз",
        "water_color": "Су түсі",
        "no_nuclear_weapon": "Ядролық қарусыз",
        "sandbox": "Құмсалғыш",
        "turn": "Жүріс",
        "player_land": "Ойыншы елі",
        "fog_of_war": "Соғыс тұманы",
        "map_hash": "Карта хэші",
        "min_game_version": "Минималды ойын нұсқасы",

        // Оқиғалар
        "event_image": "Оқиға суреті",
        "event_icon": "Оқиға белгішесі",
        "event_group": "Оқиға тобы",
        "event_name": "Оқиға атауы",
        "event_title": "Оқиға тақырыбы",
        "event_description": "Оқиға сипаттамасы",
        "event_hide_later": "Кейін жасыру",
        "event_delete_turns": "Жою (жүрістер)",
        "answer_text": "Жауап мәтіні",
        "result_description": "Нәтиже сипаттамасы",
        "auto_select_if_ignored": "Елемегенде таңдау",
        "enable_answer": "Жауапты қосу",

        // Талаптар және бонустар
        "requirements_editor": "Талаптар редакторы",
        "bonus_editor": "Бонустар редакторы",
        "type": "Түрі",
        "subtype": "Қосымша түрі",
        "action": "Әрекет",
        "value": "Мән",
        "more": "Көп",
        "equal": "Тең",
        "not_equal": "Тең емес",
        "less": "Аз",

        // Талаптар түрлері
        "defense": "Қорғанысты өзгерту",
        "attack": "Шабуылды өзгерту",
        "building_cost": "Құрылыс құнын өзгерту",
        "discontent": "Наразылықты өзгерту",
        "population_income": "Халық табысын өзгерту",
        "add_random_culture_population": "Халық қосу",
        "prestige": "Беделді өзгерту",
        "science": "Змяніць науку",
        "money": "Змяніць грошы",
        "add_oil": "Мұнай қосу",
        "add_cruiser": "Добавить крейсер",
        "add_battleship": "Добавить линкор",
        "add_tank": "Добавить танк",
        "add_shock_infantry": "Добавить ударную піхоту",
        "add_infantry": "Добавить піхоту",
        "army_losses": "Втрати армії",
        "relation_ideology_change": "Идеологиямен қарым-қатынасты өзгерту",
        "relation_change": "Змяніць адносіны",
        "diplomacy_lift_sanctions": "Зняць санкцыі",
        "diplomacy_sanctions": "Накласці санкцыі",
        "diplomacy_pact": "Укласти пакт",
        "diplomacy_alliance": "Укласти альянс",
        "diplomacy_peace": "Укласти мир",
        "diplomacy_war": "Оголосити вайну",
        "resurrect_country": "Відновити країну",
        "annex_country": "Анексувати країну",
        "duration": "Длительность (ходов)"
    }
}; 