const translations = {
    "en": {
        // Main page
        "editor": "Editor",
        "countries": "Countries",
        "events": "Events",
        "save": "Save",
        "drag_file_here": "Drag file here or",
        "choose_file": "Choose file",
        "file_preview": "File preview",
        "changes_not_saved": "Changes not saved",

        // Settings form
        "title": "Title",
        "id": "ID",
        "last_turn": "Last Turn",
        "year": "Year",
        "month": "Month",
        "play_after_last_turn": "Play After Last Turn",
        "technology_lvl": "Technology Level",
        "technologies_are_opened": "All Technologies Opened",
        "resources_spawn": "Resources Spawn",
        "difficulty": "Difficulty",
        "bots_behavior": "Bots Behavior",
        "no_initial_diplomacy": "No Initial Diplomacy",
        "water_color": "Water Color",
        "no_nuclear_weapon": "No Nuclear Weapon",
        "sandbox": "Sandbox",
        "turn": "Turn",
        "player_land": "Player Country",
        "fog_of_war": "Fog of War",
        "map_hash": "Map Hash",
        "num_of_provinces": "Number of Provinces",
        "min_game_version": "Minimum Game Version",

        // Dropdown values
        "easy": "Easy",
        "standard": "Standard",
        "hard": "Hard",
        "impossible": "Impossible",
        "peaceful": "Peaceful",
        "aggressive": "Aggressive",
        "low": "Low",
        "few": "Few",
        "enabled": "Yes",
        "disabled": "No",

        // Countries page
        "countries_title": "Countries",
        "remove_invalid_owners": "Remove Invalid Owners",
        "add_country": "Add Country",
        "color": "Color",
        "name": "Name",
        "system_name": "System Name",
        "provinces_count": "Provinces Count",
        "capital": "Capital",
        "capital_name": "Capital Name",
        "capital_id": "Capital ID",
        "defeated": "Defeated",
        "political_system": "Political System",
        "democracy": "Democracy",
        "monarchy": "Monarchy",
        "communism": "Communism",
        "fascism": "Fascism",
        "anarchy": "Anarchy",
        "allies": "Allies",
        "enemies": "Enemies",
        "independence_guarantees": "Independence Guarantees",
        "guaranteed_by": "Guaranteed By",
        "pacts": "Pacts",
        "sanctions": "Sanctions",
        "vassals": "Vassals",
        "color_r": "R",
        "color_g": "G",
        "color_b": "B",

        // Country edit
        "edit_country": "Edit country",
        "reforms": "Reforms",
        "copy": "Copy",
        "delete": "Delete",
        "add_country_button": "Add country",
        "add": "Add",
        "choose_country": "Choose country",
        "choose_country...": "Choose country...",
        "turn:": "Turn:",

        // Events page
        "events_title": "Events",
        "add_event": "Add event",
        "event_id": "ID",
        "event_group": "Group",
        "event_name": "Name",
        "event_title": "Title",

        // Event edit
        "edit_event": "Edit event",
        "event_image": "Event Image:",
        "event_icon": "Event Icon:",
        "event_group_name": "Group",
        "event_unique_name": "System name",
        "event_hide_later": "Hide later",
        "event_delete_turns": "Delete after (turns)",
        "event_description": "Event description",
        "general_requirements": "General requirements",
        "answer_1": "Answer 1",
        "answer_2": "Answer 2",
        "answer_3": "Answer 3",
        "answer_text": "Answer text",
        "result_description": "Result description",
        "auto_select": "Auto-select if ignored",
        "enable_answer": "Enable answer",
        "requirements": "Requirements",
        "bonuses": "Bonuses",
        "common_requirements": "Common requirements",

        // Requirements editor
        "requirements_editor": "Requirements Editor",
        "bonus_editor": "Bonus Editor",
        "type": "Type",
        "subtype": "Subtype",
        "action": "Action",
        "value": "Value",
        "province": "Province",
        "country": "Country",
        "resource": "Resource",
        "more": "More",
        "equal": "Equal",
        "not_equal": "Not Equal",
        "less": "Less",

        // Reforms page
        "reforms_title": "Reforms",
        "add_reform": "Add reform",
        "paste": "Paste",
        "required_ideology": "Required ideology",
        "provinces_amount": "Provinces amount",
        "actions": "Actions",

        // Reform edit
        "edit_reform": "Edit reform",
        "back": "Back",
        "copy_to_buffer": "Copy to buffer",
        "load_for_sync": "Load for sync",
        "new_reform": "New reform",

        // Common
        "yes": "Yes",
        "no": "No",
        "edit": "Edit",
        "select_country": "Select country",
        "select_country_placeholder": "Select country...",
        "turn_number": "Turn:",

        // Modal windows
        "new_country": "New Country",
        "create": "Create",
        "fill_all_fields": "Please fill in all fields",
        "country_exists": "Country with this ID already exists",
        "relation_params": "Relation Parameters",
        "relation_turn": "Start Turn",
        "relation_duration": "Duration",
        "relation_initiator": "Initiator",

        // Country names
        "country_civilization_13": "Great Britain",
        "country_civilization_21": "France",
        "country_civilization_22": "Russian Empire",
        "country_undeveloped_land": "Undeveloped Land",

        // File upload section
        "drag_file_here_or": "Drag file here or",
        "choose_file": "Choose file",
        "file_preview": "File preview",
        "event_id": "ID",
        "event_group": "Group",
        "event_unique_name": "System name",
        "event_title": "Title",
        "event_hide_later": "Hide later",
        "event_delete_turns": "Delete after (turns)",
        "event_description": "Event description",
        "answer_text": "Answer text",
        "result_description": "Result description",
        "auto_select_if_ignored": "Auto-select if ignored",
        "reforms_of": "Reforms of",
        "copy_suffix": "copy",
        "function_in_development": "This function is under development",
        "many": "Many",

        // Event images and icons
        "image_preview": "Image preview",
        "icon_preview": "Icon preview",
        
        // Main page settings
        "file_parse_error": "File parse error",
        "file_access_error": "File access error",
        "file_saved": "File saved",
        "file_downloaded": "File downloaded",
        "file_update_error": "File update error",
        "water_color_update_error": "Water color update error",

        // Reform colors
        "random_color": "R",

        // Answers
        "answer_1_title": "Answer 1",
        "answer_2_title": "Answer 2",
        "answer_3_title": "Answer 3",

        // Account dropdown
        "profile": "Profile",
        "logout": "Logout",

        // Account menu
        "guest": "Guest",
        "login": "Login with Discord",
        "register": "Register",
        "settings": "Settings",

        // Button tooltips
        "remove_invalid_owners_tooltip": "Remove Invalid Owners\nRemoves countries that have no provinces on the map",
        "add_country_tooltip": "Add Country\nCreate a new country with default settings",
        "copy_tooltip": "Copy\nCreate a duplicate of the current item",
        "delete_tooltip": "Delete\nPermanently remove this item",
        "add_reform_tooltip": "Add Reform\nCreate a new reform for the current country",
        "paste_tooltip": "Paste\nAdd a reform from the buffer",
        "back_tooltip": "Back\nReturn to the previous page",
        "copy_buffer_tooltip": "Copy to Buffer\nCopy the current reform to buffer for pasting",
        "load_sync_tooltip": "Load for Sync\nLoad reform data for synchronization",
        "add_event_tooltip": "Add Event\nCreate a new event",
        "add_requirement_tooltip": "Add\nAdd a new requirement or bonus",
        "save_tooltip": "Save\nSave current changes",
        "cancel_tooltip": "Cancel\nDiscard changes and close",
        "reforms_tooltip": "Reforms\nManage country reforms"
    },
    "ru": {
        // Главная страница
        "editor": "Редактор",
        "countries": "Страны",
        "events": "События",
        "save": "Сохранить",
        "drag_file_here": "Перетащите файл сюда или",
        "choose_file": "Выберите файл",
        "file_preview": "Предпросмотр файла",
        "changes_not_saved": "Изменения не сохранены",

        // Форма настроек
        "title": "Название",
        "id": "ID",
        "last_turn": "Последний Ход",
        "year": "Год",
        "month": "Месяц",
        "play_after_last_turn": "Игра После Последнего Хода",
        "technology_lvl": "Уровень Технологий",
        "technologies_are_opened": "Открыты Все Технологии",
        "resources_spawn": "Спаун Ресурсов",
        "difficulty": "Сложность",
        "bots_behavior": "Поведение Ботов",
        "no_initial_diplomacy": "Без Стартовой Дипломатии",
        "water_color": "Цвет Воды",
        "no_nuclear_weapon": "Без Ядерного Оружия",
        "sandbox": "Песочница",
        "turn": "Ход",
        "player_land": "Страна Игрока",
        "fog_of_war": "Туман Войны",
        "map_hash": "Хэш Карты",
        "num_of_provinces": "Количество Провинций",
        "min_game_version": "Минимальная Версия Игры",

        // Значения выпадающих списков
        "easy": "Легко",
        "standard": "Нормально",
        "hard": "Сложно",
        "impossible": "Невозможно",
        "peaceful": "Мирные",
        "aggressive": "Агрессивные",
        "low": "Мало",
        "few": "Много",
        "enabled": "Да",
        "disabled": "Нет",

        // Страница стран
        "countries_title": "Страны",
        "remove_invalid_owners": "Удалить пустых владельцев",
        "add_country": "Добавить страну",
        "color": "Цвет",
        "name": "Название",
        "system_name": "Системное название",
        "provinces_count": "Количество провинций",
        "capital": "Столица",
        "capital_name": "Название столицы",
        "capital_id": "ID столицы",
        "defeated": "Побеждена",
        "political_system": "Политический строй",
        "democracy": "Демократия",
        "monarchy": "Монархия",
        "communism": "Коммунизм",
        "fascism": "Фашизм",
        "anarchy": "Анархия",
        "allies": "Союзники",
        "enemies": "Враги",
        "independence_guarantees": "Гарантии независимости",
        "guaranteed_by": "Гарантии от",
        "pacts": "Пакты",
        "sanctions": "Санкции",
        "vassals": "Вассалы",
        "color_r": "К",
        "color_g": "З",
        "color_b": "С",

        // Country edit
        "edit_country": "Редактирование страны",
        "reforms": "Реформы",
        "copy": "Копировать",
        "delete": "Удалить",
        "add_country_button": "Добавить страну",

        // Страница событий
        "events_title": "События",
        "add_event": "Добавить событие",
        "event_id": "ID",
        "event_group": "Группа",
        "event_name": "Название",
        "event_title": "Заголовок",

        // Редактирование события
        "edit_event": "Редактирование события",
        "event_image": "Картинка события:",
        "event_icon": "Иконка события:",
        "event_group_name": "Группа",
        "event_unique_name": "Системное название",
        "event_hide_later": "Прятать позже",
        "event_delete_turns": "Удалить через (ходов)",
        "event_description": "Описание события",
        "general_requirements": "Общие требования",
        "answer_1": "Ответ 1",
        "answer_2": "Ответ 2",
        "answer_3": "Ответ 3",
        "answer_text": "Текст ответа",
        "result_description": "Описание результата",
        "auto_select": "Выбирать при игнорировании",
        "enable_answer": "Включить ответ",
        "requirements": "Требования",
        "bonuses": "Бонусы",
        "common_requirements": "Общие требования",

        // Редактор требований и бонусов
        "requirements_editor": "Редактор требований",
        "bonus_editor": "Редактор бонусов",
        "type": "Тип",
        "subtype": "Подтип",
        "action": "Действие",
        "value": "Значение",
        "province": "Провинция",
        "country": "Страна",
        "resource": "Ресурс",
        "more": "Больше",
        "equal": "Равно",
        "not_equal": "Не равно",
        "less": "Меньше",

        // Страница реформ
        "reforms_title": "Реформы",
        "add_reform": "Добавить реформу",
        "paste": "Вставить",
        "required_ideology": "Требуемая идеология",
        "provinces_amount": "Количество провинций",
        "actions": "Действия",

        // Редактирование реформы
        "edit_reform": "Редактирование реформы",
        "back": "Назад",
        "copy_to_buffer": "Копировать в буфер",
        "load_for_sync": "Загрузить для синхронизации",
        "new_reform": "Новая реформа",

        // Общие
        "yes": "Да",
        "no": "Нет",
        "edit": "Редактировать",
        "select_country": "Выберите страну",
        "select_country_placeholder": "Выберите страну...",
        "turn_number": "Ход:",

        // Модальные окна
        "new_country": "Новая страна",
        "create": "Создать",
        "fill_all_fields": "Пожалуйста, заполните все поля",
        "country_exists": "Страна с таким ID уже существует",
        "relation_params": "Параметры отношений",
        "relation_turn": "Ход начала",
        "relation_duration": "Длительность",
        "relation_initiator": "Инициатор",

        // Названия стран
        "country_civilization_13": "Великобритания",
        "country_civilization_21": "Франция",
        "country_civilization_22": "Российская Империя",
        "country_undeveloped_land": "Неразвитые земли",

        // File upload section
        "drag_file_here_or": "Перетащите файл сюда или",
        "choose_file": "Выберите файл",
        "file_preview": "Предпросмотр файла",
        "event_id": "ID",
        "event_group": "Группа",
        "event_unique_name": "Системное название",
        "event_title": "Заголовок",
        "event_hide_later": "Прятать позже",
        "event_delete_turns": "Удалить через (ходов)",
        "event_description": "Описание события",
        "answer_text": "Текст ответа",
        "result_description": "Описание результата",
        "auto_select_if_ignored": "Выбирать при игнорировании",
        "reforms_of": "Реформы",
        "copy_suffix": "копия",
        "function_in_development": "Эта функция находится в разработке",
        "many": "Много",

        // Event images and icons
        "image_preview": "Предпросмотр картинки",
        "icon_preview": "Предпросмотр иконки",
        
        // Main page settings
        "file_parse_error": "Ошибка чтения файла",
        "file_access_error": "Ошибка доступа к файлу",
        "file_saved": "Файл сохранен",
        "file_downloaded": "Файл скачан",
        "file_update_error": "Ошибка обновления файла",
        "water_color_update_error": "Ошибка обновления цвета воды",

        // Reform colors
        "random_color": "R",

        // Answers
        "answer_1_title": "Ответ 1",
        "answer_2_title": "Ответ 2",
        "answer_3_title": "Ответ 3",

        // Выпадающее меню аккаунта
        "profile": "Профиль",
        "logout": "Выйти",

        // Account menu
        "guest": "Гость",
        "login": "Войти через Discord",
        "register": "Регистрация",
        "settings": "Настройки",

        // Button tooltips
        "remove_invalid_owners_tooltip": "Удалить пустых владельцев\nУдаляет страны, не имеющие провинций на карте",
        "add_country_tooltip": "Добавить страну\nСоздать новую страну с настройками по умолчанию",
        "copy_tooltip": "Копировать\nСоздать дубликат текущего элемента",
        "delete_tooltip": "Удалить\nБезвозвратно удалить этот элемент",
        "add_reform_tooltip": "Добавить реформу\nСоздать новую реформу для текущей страны",
        "paste_tooltip": "Вставить\nДобавить реформу из буфера",
        "back_tooltip": "Назад\nВернуться на предыдущую страницу",
        "copy_buffer_tooltip": "Копировать в буфер\nСкопировать текущую реформу в буфер для вставки",
        "load_sync_tooltip": "Загрузить для синхронизации\nЗагрузить данные реформы для синхронизации",
        "add_event_tooltip": "Добавить событие\nСоздать новое событие",
        "add_requirement_tooltip": "Добавить\nДобавить новое требование или бонус",
        "save_tooltip": "Сохранить\nСохранить текущие изменения",
        "cancel_tooltip": "Отмена\nОтменить изменения и закрыть",
        "reforms_tooltip": "Реформы\nУправление реформами страны"
    },
    "uk": {
        // Головна сторінка
        "editor": "Редактор",
        "countries": "Країни",
        "events": "Події",
        "save": "Зберегти",
        "drag_file_here": "Перетягніть файл сюди або",
        "choose_file": "Виберіть файл",
        "file_preview": "Попередній перегляд файлу",
        "changes_not_saved": "Зміни не збережені",

        // Форма налаштувань
        "title": "Назва",
        "id": "ID",
        "last_turn": "Останній Хід",
        "year": "Рік",
        "month": "Місяць",
        "play_after_last_turn": "Гра Після Останнього Ходу",
        "technology_lvl": "Рівень Технологій",
        "technologies_are_opened": "Відкриті Всі Технології",
        "resources_spawn": "Спаун Ресурсів",
        "difficulty": "Складність",
        "bots_behavior": "Поведінка Ботів",
        "no_initial_diplomacy": "Без Початкової Дипломатії",
        "water_color": "Колір Води",
        "no_nuclear_weapon": "Без Ядерної Зброї",
        "sandbox": "Пісочниця",
        "turn": "Хід",
        "player_land": "Країна Гравця",
        "fog_of_war": "Туман Війни",
        "map_hash": "Хеш Карти",
        "num_of_provinces": "Кількість Провінцій",
        "min_game_version": "Мінімальна Версія Гри",

        // Значення випадаючих списків
        "easy": "Легко",
        "standard": "Нормально",
        "hard": "Складно",
        "impossible": "Неможливо",
        "peaceful": "Мирні",
        "aggressive": "Агресивні",
        "low": "Мало",
        "few": "Багато",
        "enabled": "Так",
        "disabled": "Ні",

        // Сторінка країн
        "countries_title": "Країни",
        "remove_invalid_owners": "Видалити порожніх власників",
        "add_country": "Додати країну",
        "color": "Колір",
        "name": "Назва",
        "system_name": "Системна назва",
        "provinces_count": "Кількість провінцій",
        "capital": "Столиця",
        "capital_name": "Назва столиці",
        "capital_id": "ID столиці",
        "defeated": "Переможена",
        "political_system": "Політичний устрій",
        "democracy": "Демократія",
        "monarchy": "Монархія",
        "communism": "Комунізм",
        "fascism": "Фашизм",
        "anarchy": "Анархія",
        "allies": "Союзники",
        "enemies": "Вороги",
        "independence_guarantees": "Гарантії незалежності",
        "guaranteed_by": "Гарантії від",
        "pacts": "Пакти",
        "sanctions": "Санкції",
        "vassals": "Васали",
        "color_r": "Ч",
        "color_g": "З",
        "color_b": "С",

        // Редагування країни
        "edit_country": "Редагування країни",
        "reforms": "Реформи",
        "copy": "Копіювати",
        "delete": "Видалити",
        "add_country_button": "Додати країну",

        // Сторінка подій
        "events_title": "Події",
        "add_event": "Додати подію",
        "event_id": "ID",
        "event_group": "Група",
        "event_name": "Назва",
        "event_title": "Заголовок",

        // Редагування події
        "edit_event": "Редагування події",
        "event_image": "Зображення події:",
        "event_icon": "Іконка події:",
        "event_group_name": "Група",
        "event_unique_name": "Системна назва",
        "event_hide_later": "Приховати пізніше",
        "event_delete_turns": "Видалити через (ходів)",
        "event_description": "Опис події",
        "general_requirements": "Загальні вимоги",
        "answer_1": "Відповідь 1",
        "answer_2": "Відповідь 2",
        "answer_3": "Відповідь 3",
        "answer_text": "Текст відповіді",
        "result_description": "Опис результату",
        "auto_select": "Вибирати при ігноруванні",
        "enable_answer": "Увімкнути відповідь",
        "requirements": "Вимоги",
        "bonuses": "Бонуси",
        "common_requirements": "Загальні вимоги",

        // Редактор вимог та бонусів
        "requirements_editor": "Редактор вимог",
        "bonus_editor": "Редактор бонусів",
        "type": "Тип",
        "subtype": "Підтип",
        "action": "Дія",
        "value": "Значення",
        "province": "Провінція",
        "country": "Країна",
        "resource": "Ресурс",
        "more": "Більше",
        "equal": "Дорівнює",
        "not_equal": "Не дорівнює",
        "less": "Менше",

        // Сторінка реформ
        "reforms_title": "Реформи",
        "add_reform": "Додати реформу",
        "paste": "Вставити",
        "required_ideology": "Необхідна ідеологія",
        "provinces_amount": "Кількість провінцій",
        "actions": "Дії",

        // Редагування реформи
        "edit_reform": "Редагування реформи",
        "back": "Назад",
        "copy_to_buffer": "Копіювати в буфер",
        "load_for_sync": "Завантажити для синхронізації",
        "new_reform": "Нова реформа",

        // Загальні
        "yes": "Так",
        "no": "Ні",
        "edit": "Редагувати",
        "select_country": "Виберіть країну",
        "select_country_placeholder": "Виберіть країну...",
        "turn_number": "Хід:",

        // Модальні вікна
        "new_country": "Нова країна",
        "create": "Створити",
        "fill_all_fields": "Будь ласка, заповніть усі поля",
        "country_exists": "Країна з таким ID вже існує",
        "relation_params": "Параметри відносин",
        "relation_turn": "Хід початку",
        "relation_duration": "Тривалість",
        "relation_initiator": "Ініціатор",

        // Назви країн
        "country_civilization_13": "Велика Британія",
        "country_civilization_21": "Франція",
        "country_civilization_22": "Російська Імперія",
        "country_undeveloped_land": "Нерозвинені землі",

        // File upload section
        "drag_file_here_or": "Перетягніть файл сюди або",
        "choose_file": "Виберіть файл",
        "file_preview": "Попередній перегляд файлу",
        "event_id": "ID",
        "event_group": "Група",
        "event_unique_name": "Системна назва",
        "event_title": "Заголовок",
        "event_hide_later": "Приховати пізніше",
        "event_delete_turns": "Видалити через (ходів)",
        "event_description": "Опис події",
        "answer_text": "Текст відповіді",
        "result_description": "Опис результату",
        "auto_select_if_ignored": "Вибирати при ігноруванні",
        "reforms_of": "Реформи",
        "copy_suffix": "копія",
        "function_in_development": "Ця функція знаходиться в розробці",
        "many": "Багато",

        // Event images and icons
        "image_preview": "Попередній перегляд зображення",
        "icon_preview": "Попередній перегляд іконки",
        
        // Main page settings
        "file_parse_error": "Помилка читання файлу",
        "file_access_error": "Помилка доступу до файлу",
        "file_saved": "Файл збережено",
        "file_downloaded": "Файл завантажено",
        "file_update_error": "Помилка оновлення файлу",
        "water_color_update_error": "Помилка оновлення кольору води",

        // Reform colors
        "random_color": "R",

        // Answers
        "answer_1_title": "Відповідь 1",
        "answer_2_title": "Відповідь 2",
        "answer_3_title": "Відповідь 3",

        // Випадаюче меню облікового запису
        "profile": "Профіль",
        "logout": "Вийти",

        // Account menu
        "guest": "Гість",
        "login": "Увійти через Discord",
        "register": "Реєстрація",
        "settings": "Налаштування",

        // Button tooltips
        "remove_invalid_owners_tooltip": "Видалити порожніх власників\nВидаляє країни, що не мають провінцій на карті",
        "add_country_tooltip": "Додати країну\nСтворити нову країну з налаштуваннями за замовчуванням",
        "copy_tooltip": "Копіювати\nСтворити дублікат поточного елемента",
        "delete_tooltip": "Видалити\nБезповоротно видалити цей елемент",
        "add_reform_tooltip": "Додати реформу\nСтворити нову реформу для поточної країни",
        "paste_tooltip": "Вставити\nДодати реформу з буфера",
        "back_tooltip": "Назад\nПовернутися на попередню сторінку",
        "copy_buffer_tooltip": "Копіювати в буфер\nСкопіювати поточну реформу в буфер для вставки",
        "load_sync_tooltip": "Завантажити для синхронізації\nЗавантажити дані реформи для синхронізації",
        "add_event_tooltip": "Додати подію\nСтворити нову подію",
        "add_requirement_tooltip": "Додати\nДодати нову вимогу або бонус",
        "save_tooltip": "Зберегти\nЗберегти поточні зміни",
        "cancel_tooltip": "Скасувати\nСкасувати зміни та закрити",
        "reforms_tooltip": "Реформи\nУправління реформами країни"
    }
}; 