const translations = {
    "en": {
        // Main page
        "editor": "Editor",
        "countries": "Countries",
        "events": "Events",
        "save": "Save",
        "drag_file_here": "Drag file here or",
        "choose_file": "Choose file",
        "file_preview": "File preview",
        "changes_not_saved": "Changes not saved",

        // Settings form
        "title": "Title",
        "id": "ID",
        "last_turn": "Last Turn",
        "year": "Year",
        "month": "Month",
        "play_after_last_turn": "Play After Last Turn",
        "technology_lvl": "Technology Level",
        "technologies_are_opened": "All Technologies Opened",
        "resources_spawn": "Resources Spawn",
        "difficulty": "Difficulty",
        "bots_behavior": "Bots Behavior",
        "no_initial_diplomacy": "No Initial Diplomacy",
        "water_color": "Water Color",
        "no_nuclear_weapon": "No Nuclear Weapon",
        "sandbox": "Sandbox",
        "turn": "Turn",
        "player_land": "Player Country",
        "fog_of_war": "Fog of War",
        "map_hash": "Map Hash",
        "num_of_provinces": "Number of Provinces",
        "min_game_version": "Minimum Game Version",

        // Dropdown values
        "easy": "Easy",
        "standard": "Standard",
        "hard": "Hard",
        "impossible": "Impossible",
        "peaceful": "Peaceful",
        "aggressive": "Aggressive",
        "low": "Low",
        "few": "Few",
        "enabled": "Yes",
        "disabled": "No",

        // Countries page
        "countries_title": "Countries",
        "remove_invalid_owners": "Remove Invalid Owners",
        "add_country": "Add Country",
        "color": "Color",
        "name": "Name",
        "system_name": "System Name",
        "provinces_count": "Provinces Count",
        "capital": "Capital",
        "capital_name": "Capital Name",
        "capital_id": "Capital ID",
        "defeated": "Defeated",
        "political_system": "Political System",
        "democracy": "Democracy",
        "monarchy": "Monarchy",
        "communism": "Communism",
        "fascism": "Fascism",
        "anarchy": "Anarchy",
        "allies": "Allies",
        "enemies": "Enemies",
        "independence_guarantees": "Independence Guarantees",
        "guaranteed_by": "Guaranteed By",
        "pacts": "Pacts",
        "sanctions": "Sanctions",
        "vassals": "Vassals",
        "color_r": "R",
        "color_g": "G",
        "color_b": "B",

        // Country edit
        "edit_country": "Edit country",
        "reforms": "Reforms",
        "copy": "Copy",
        "delete": "Delete",
        "add_country_button": "Add country",
        "add": "Add",
        "choose_country": "Choose country",
        "choose_country...": "Choose country...",
        "turn:": "Turn:",

        // Events page
        "events_title": "Events",
        "add_event": "Add event",
        "event_id": "ID",
        "event_group": "Group",
        "event_name": "Name",
        "event_title": "Title",

        // Event edit
        "edit_event": "Edit event",
        "event_image": "Event Image:",
        "event_icon": "Event Icon:",
        "event_group_name": "Group",
        "event_unique_name": "System name",
        "event_hide_later": "Hide later",
        "event_delete_turns": "Delete after (turns)",
        "event_description": "Event description",
        "general_requirements": "General requirements",
        "answer_1": "Answer 1",
        "answer_2": "Answer 2",
        "answer_3": "Answer 3",
        "answer_text": "Answer text",
        "result_description": "Result description",
        "auto_select": "Auto-select if ignored",
        "enable_answer": "Enable answer",
        "requirements": "Requirements",
        "bonuses": "Bonuses",
        "common_requirements": "Common requirements",

        "save": "Save",
        "cancel": "Cancel",
        "add": "Add",

        // Requirements editor
        "requirements_editor": "Requirements Editor",
        "bonus_editor": "Bonus Editor",
        "type": "Type",
        "subtype": "Subtype",
        "action": "Action",
        "value": "Value",
        "enter_number": "Enter number",
        "enter_percent": "Enter percent",
        "enter_value": "Enter value",
        "enter_building_name": "Enter building name",
        "enter_institution_name": "Enter institution name",

        // Requirement types
        "defense": "Change defense",
        "attack": "Change attack",
        "building_cost": "Change building cost",
        "discontent": "Change discontent",
        "population_income": "Change population income",
        "add_random_culture_population": "Add population",
        "prestige": "Change prestige",
        "science": "Change science",
        "money": "Change money",
        "add_oil": "Add oil",
        "add_cruiser": "Add cruiser",
        "add_battleship": "Add battleship",
        "add_tank": "Add tank",
        "add_shock_infantry": "Add shock infantry",
        "add_infantry": "Add infantry",
        "army_losses": "Army losses",
        "relation_ideology_change": "Change ideology relations",
        "relation_change": "Change relations",
        "diplomacy_lift_sanctions": "Lift sanctions",
        "diplomacy_sanctions": "Impose sanctions",
        "diplomacy_pact": "Sign pact",
        "diplomacy_alliance": "Form alliance",
        "diplomacy_peace": "Make peace",
        "diplomacy_war": "Declare war",
        "resurrect_country": "Resurrect country",
        "annex_country": "Annex country",

        // Reforms page
        "reforms_title": "Reforms",
        "add_reform": "Add reform",
        "paste": "Paste",
        "required_ideology": "Required ideology",
        "provinces_amount": "Provinces amount",
        "actions": "Actions",

        // Reform edit
        "edit_reform": "Edit reform",
        "back": "Back",
        "copy_to_buffer": "Copy to buffer",
        "load_for_sync": "Load for sync",
        "new_reform": "New reform",

        // Common
        "yes": "Yes",
        "no": "No",
        "edit": "Edit",
        "select_country": "Select country",
        "select_country_placeholder": "Select country...",
        "turn_number": "Turn:",

        // Modal windows
        "new_country": "New Country",
        "create": "Create",
        "fill_all_fields": "Please fill in all fields",
        "country_exists": "Country with this ID already exists",
        "relation_params": "Relation Parameters",
        "relation_turn": "Start Turn",
        "relation_duration": "Duration",
        "relation_initiator": "Initiator",
        "relation_turn_short": "Turn",
        "relation_duration_short": "Duration",
        "relation_initiator_short": "Initiator",

        // Country names
        "country_civilization_13": "Great Britain",
        "country_civilization_21": "France",
        "country_civilization_22": "Russian Empire",
        "country_undeveloped_land": "Undeveloped Land",

        // File upload section
        "drag_file_here_or": "Drag file here or",
        "choose_file": "Choose file",
        "file_preview": "File preview",
        "event_id": "ID",
        "event_group": "Group",
        "event_unique_name": "System name",
        "event_title": "Title",
        "event_hide_later": "Hide later",
        "event_delete_turns": "Delete after (turns)",
        "event_description": "Event description",
        "answer_text": "Answer text",
        "result_description": "Result description",
        "auto_select_if_ignored": "Auto-select if ignored",
        "reforms_of": "Reforms of",
        "copy_suffix": "copy",
        "function_in_development": "This function is under development",
        "many": "Many",

        // Event images and icons
        "image_preview": "Image preview",
        "icon_preview": "Icon preview",
        
        // Main page settings
        "file_parse_error": "File parse error",
        "file_access_error": "File access error",
        "file_saved": "File saved",
        "file_downloaded": "File downloaded",
        "file_update_error": "File update error",
        "water_color_update_error": "Water color update error",

        // Reform colors
        "random_color": "R",

        // Answers
        "answer_1_title": "Answer 1",
        "answer_2_title": "Answer 2",
        "answer_3_title": "Answer 3",

        // Account dropdown
        "profile": "Profile",
        "logout": "Logout",

        // Requirement types
        "year": "Year",
        "month": "Month",
        "turn": "Turn",
        "land_id": "Country ID",
        "land_name": "Country name",
        "near_water": "Near water",
        "has_pact": "Has pact",
        "has_sanctions": "Has sanctions",
        "has_war": "Has war",
        "enemy_near_capital": "Enemy near capital",
        "lost_capital": "Lost capital",
        "is_defeated": "Is defeated",
        "land_power": "Country power",
        "independent_land": "Independent country",
        "no_enemy": "No enemy",
        "random_value": "Random value",
        "count_of_tasks": "Count of tasks",
        "tax": "Tax",
        "building_exists": "Building exists",
        "political_institution": "Political institution",

        // Actions
        "more": "More",
        "equal": "Equal",
        "not_equal": "Not equal",
        "less": "Less"
    },
    "ru": {
        // Главная страница
        "editor": "Редактор",
        "countries": "Страны",
        "events": "События",
        "save": "Сохранить",
        "drag_file_here": "Перетащите файл сюда или",
        "choose_file": "Выберите файл",
        "file_preview": "Предпросмотр файла",
        "changes_not_saved": "Изменения не сохранены",

        // Форма настроек
        "title": "Название",
        "id": "ID",
        "last_turn": "Последний Ход",
        "year": "Год",
        "month": "Месяц",
        "play_after_last_turn": "Игра После Последнего Хода",
        "technology_lvl": "Уровень Технологий",
        "technologies_are_opened": "Открыты Все Технологии",
        "resources_spawn": "Спаун Ресурсов",
        "difficulty": "Сложность",
        "bots_behavior": "Поведение Ботов",
        "no_initial_diplomacy": "Без Стартовой Дипломатии",
        "water_color": "Цвет Воды",
        "no_nuclear_weapon": "Без Ядерного Оружия",
        "sandbox": "Sandbox",
        "turn": "Ход",
        "player_land": "Страна Игрока",
        "fog_of_war": "Туман Войны",
        "map_hash": "Хэш Карты",
        "num_of_provinces": "Количество Провинций",
        "min_game_version": "Минимальная Версия Игры",

        // Значения выпадающих списков
        "easy": "Легко",
        "standard": "Стандартно",
        "hard": "Сложно",
        "impossible": "Невозможно",
        "peaceful": "Мирные",
        "aggressive": "Агрессивные",
        "low": "Мало",
        "few": "Много",
        "enabled": "Да",
        "disabled": "Нет",

        // Страница стран
        "countries_title": "Страны",
        "remove_invalid_owners": "Удалить пустых владельцев",
        "add_country": "Добавить страну",
        "color": "Цвет",
        "name": "Название",
        "system_name": "Системное название",
        "provinces_count": "Количество провинций",
        "capital": "Столица",
        "capital_name": "Название столицы",
        "capital_id": "ID столицы",
        "defeated": "Побеждена",
        "political_system": "Политический строй",
        "democracy": "Демократия",
        "monarchy": "Монархия",
        "communism": "Коммунизм",
        "fascism": "Фашизм",
        "anarchy": "Анархия",
        "allies": "Союзники",
        "enemies": "Враги",
        "independence_guarantees": "Гарантии независимости",
        "guaranteed_by": "Гарантии от",
        "pacts": "Пакты",
        "sanctions": "Санкции",
        "vassals": "Вассалы",
        "color_r": "R",
        "color_g": "G",
        "color_b": "B",

        // Country edit
        "edit_country": "Редактирование страны",
        "reforms": "Реформы",
        "copy": "Копировать",
        "delete": "Удалить",
        "add_country_button": "Добавить страну",

        // Страница событий
        "events_title": "События",
        "add_event": "Добавить событие",
        "event_id": "ID",
        "event_group": "Группа",
        "event_name": "Название",
        "event_title": "Заголовок",

        // Редактирование события
        "edit_event": "Редактирование события",
        "event_image": "Картинка события:",
        "event_icon": "Иконка события:",
        "event_group_name": "Группа",
        "event_unique_name": "Системное название",
        "event_hide_later": "Прятать позже",
        "event_delete_turns": "Удалить через (ходов)",
        "event_description": "Описание события",
        "general_requirements": "Общие требования",
        "answer_1": "Ответ 1",
        "answer_2": "Ответ 2",
        "answer_3": "Ответ 3",
        "answer_text": "Текст ответа",
        "result_description": "Описание результата",
        "auto_select": "Выбирать при игнорировании",
        "enable_answer": "Включить ответ",
        "requirements": "Требования",
        "bonuses": "Бонусы",
        "common_requirements": "Общие требования",

        "save": "Сохранить",
        "cancel": "Отмена",
        "add": "Добавить",

        // Редактор требований
        "requirements_editor": "Редактор требований",
        "bonus_editor": "Редактор бонусов",
        "type": "Тип",
        "subtype": "Подтип",
        "action": "Действие",
        "value": "Значение",
        "enter_number": "Введите число",
        "enter_percent": "Введите процент",
        "enter_value": "Введите значение",
        "enter_building_name": "Введите название здания",
        "enter_institution_name": "Введите название института",

        // Типы требований
        "defense": "Изменить защиту",
        "attack": "Изменить атаку",
        "building_cost": "Изменить стоимость строительства",
        "discontent": "Изменить недовольство",
        "population_income": "Изменить доход населения",
        "add_random_culture_population": "Добавить население",
        "prestige": "Изменить престиж",
        "science": "Изменить науку",
        "money": "Изменить деньги",
        "add_oil": "Добавить нефть",
        "add_cruiser": "Добавить крейсер",
        "add_battleship": "Добавить линкор",
        "add_tank": "Добавить танк",
        "add_shock_infantry": "Добавить ударную пехоту",
        "add_infantry": "Добавить пехоту",
        "army_losses": "Потери армии",
        "relation_ideology_change": "Изменить отношения с идеологией",
        "relation_change": "Изменить отношения",
        "diplomacy_lift_sanctions": "Снять санкции",
        "diplomacy_sanctions": "Наложить санкции",
        "diplomacy_pact": "Заключить пакт",
        "diplomacy_alliance": "Заключить альянс",
        "diplomacy_peace": "Заключить мир",
        "diplomacy_war": "Объявить войну",
        "resurrect_country": "Восстановить страну",
        "annex_country": "Аннексировать страну",

        // Reforms page
        "reforms_title": "Реформы",
        "add_reform": "Добавить реформу",
        "paste": "Вставить",
        "required_ideology": "Требуемая идеология",
        "provinces_amount": "Количество провинций",
        "actions": "Действия",

        // Редактирование реформы
        "edit_reform": "Редактирование реформы",
        "back": "Назад",
        "copy_to_buffer": "Копировать в буфер",
        "load_for_sync": "Загрузить для синхронизации",
        "new_reform": "Новая реформа",

        // Общие
        "yes": "Да",
        "no": "Нет",
        "edit": "Редактировать",
        "select_country": "Выберите страну",
        "select_country_placeholder": "Выберите страну...",
        "turn_number": "Ход:",

        // Модальные окна
        "new_country": "Новая страна",
        "create": "Создать",
        "fill_all_fields": "Пожалуйста, заполните все поля",
        "country_exists": "Страна с таким ID уже существует",
        "relation_params": "Параметры отношений",
        "relation_turn": "Ход начала",
        "relation_duration": "Длительность",
        "relation_initiator": "Инициатор",
        "relation_turn_short": "Ход",
        "relation_duration_short": "Длительность",
        "relation_initiator_short": "Инициатор",

        // Названия стран
        "country_civilization_13": "Великобритания",
        "country_civilization_21": "Франция",
        "country_civilization_22": "Российская Империя",
        "country_undeveloped_land": "Неразвитые земли",

        // File upload section
        "drag_file_here_or": "Перетащите файл сюда или",
        "choose_file": "Выберите файл",
        "file_preview": "Предпросмотр файла",
        "event_id": "ID",
        "event_group": "Группа",
        "event_unique_name": "Системное название",
        "event_title": "Заголовок",
        "event_hide_later": "Прятать позже",
        "event_delete_turns": "Удалить через (ходов)",
        "event_description": "Описание события",
        "answer_text": "Текст ответа",
        "result_description": "Описание результата",
        "auto_select_if_ignored": "Выбирать при игнорировании",
        "reforms_of": "Реформы",
        "copy_suffix": "копия",
        "function_in_development": "Эта функция находится в разработке",
        "many": "Много",

        // Event images and icons
        "image_preview": "Предпросмотр картинки",
        "icon_preview": "Предпросмотр иконки",
        
        // Main page settings
        "file_parse_error": "Ошибка чтения файла",
        "file_access_error": "Ошибка доступа к файлу",
        "file_saved": "Файл сохранен",
        "file_downloaded": "Файл скачан",
        "file_update_error": "Ошибка обновления файла",
        "water_color_update_error": "Ошибка обновления цвета воды",

        // Reform colors
        "random_color": "R",

        // Answers
        "answer_1_title": "Ответ 1",
        "answer_2_title": "Ответ 2",
        "answer_3_title": "Ответ 3",

        // Выпадающее меню аккаунта
        "profile": "Профиль",
        "logout": "Выйти",

        // Типы требований
        "year": "Год",
        "month": "Месяц",
        "turn": "Ход",
        "land_id": "ID страны",
        "land_name": "Название страны",
        "near_water": "Рядом с водой",
        "has_pact": "Имеет пакт",
        "has_sanctions": "Имеет санкции",
        "has_war": "В состоянии войны",
        "enemy_near_capital": "Враг у столицы",
        "lost_capital": "Потеряна столица",
        "is_defeated": "Побеждена",
        "land_power": "Сила страны",
        "independent_land": "Независимая страна",
        "no_enemy": "Нет врагов",
        "random_value": "Случайное значение",
        "count_of_tasks": "Количество заданий",
        "num_of_provinces": "Количество провинций",
        "tax": "Налог",
        "building_exists": "Здание существует",
        "political_institution": "Политический институт",

        // Действия
        "more": "Больше",
        "equal": "Равно",
        "not_equal": "Не равно",
        "less": "Меньше"
    },
    "uk": {
        // Головна сторінка
        "editor": "Редактор",
        "countries": "Країни",
        "events": "Події",
        "save": "Зберегти",
        "drag_file_here": "Перетягніть файл сюди або",
        "choose_file": "Виберіть файл",
        "file_preview": "Попередній перегляд файлу",
        "changes_not_saved": "Зміни не збережені",

        // Форма налаштувань
        "title": "Назва",
        "id": "ID",
        "last_turn": "Останній Хід",
        "year": "Рік",
        "month": "Місяць",
        "play_after_last_turn": "Гра Після Останнього Ходу",
        "technology_lvl": "Рівень Технологій",
        "technologies_are_opened": "Відкриті Всі Технології",
        "resources_spawn": "Спаун Ресурсів",
        "difficulty": "Складність",
        "bots_behavior": "Поведінка Ботів",
        "no_initial_diplomacy": "Без Стартової Дипломатії",
        "water_color": "Колір Води",
        "no_nuclear_weapon": "Без Ядерної Зброї",
        "sandbox": "Sandbox",
        "turn": "Хід",
        "player_land": "Країна Гравця",
        "fog_of_war": "Туман Війни",
        "map_hash": "Хеш Карти",
        "num_of_provinces": "Кількість Провінцій",
        "min_game_version": "Мінімальна Версія Гри",

        // Значення випадаючих списків
        "easy": "Легко",
        "standard": "Стандартно",
        "hard": "Складно",
        "impossible": "Неможливо",
        "peaceful": "Мирні",
        "aggressive": "Агресивні",
        "low": "Мало",
        "few": "Багато",
        "enabled": "Так",
        "disabled": "Ні",

        // Сторінка країн
        "countries_title": "Країни",
        "remove_invalid_owners": "Видалити порожніх власників",
        "add_country": "Додати країну",
        "color": "Колір",
        "name": "Назва",
        "system_name": "Системна назва",
        "provinces_count": "Кількість провінцій",
        "capital": "Столиця",
        "capital_name": "Назва столиці",
        "capital_id": "ID столиці",
        "defeated": "Переможена",
        "political_system": "Політичний устрій",
        "democracy": "Демократія",
        "monarchy": "Монархія",
        "communism": "Комунізм",
        "fascism": "Фашизм",
        "anarchy": "Анархія",
        "allies": "Союзники",
        "enemies": "Вороги",
        "independence_guarantees": "Гарантії незалежності",
        "guaranteed_by": "Гарантії від",
        "pacts": "Пакти",
        "sanctions": "Санкції",
        "vassals": "Васали",
        "color_r": "R",
        "color_g": "G",
        "color_b": "B",

        // Редагування країни
        "edit_country": "Редагування країни",
        "reforms": "Реформи",
        "copy": "Копіювати",
        "delete": "Видалити",
        "add_country_button": "Додати країну",

        // Сторінка подій
        "events_title": "Події",
        "add_event": "Додати подію",
        "event_id": "ID",
        "event_group": "Група",
        "event_name": "Назва",
        "event_title": "Заголовок",

        // Редагування події
        "edit_event": "Редагування події",
        "event_image": "Зображення події:",
        "event_icon": "Іконка події:",
        "event_group_name": "Група",
        "event_unique_name": "Системна назва",
        "event_hide_later": "Приховати пізніше",
        "event_delete_turns": "Видалити через (ходів)",
        "event_description": "Опис події",
        "general_requirements": "Загальні вимоги",
        "answer_1": "Відповідь 1",
        "answer_2": "Відповідь 2",
        "answer_3": "Відповідь 3",
        "answer_text": "Текст відповіді",
        "result_description": "Опис результату",
        "auto_select": "Вибирати при ігноруванні",
        "enable_answer": "Увімкнути відповідь",
        "requirements": "Вимоги",
        "bonuses": "Бонуси",
        "common_requirements": "Загальні вимоги",

        "save": "Зберегти",
        "cancel": "Скасувати",
        "add": "Додати",

        // Редактор вимог
        "requirements_editor": "Редактор вимог",
        "bonus_editor": "Редактор бонусів",
        "type": "Тип",
        "subtype": "Підтип",
        "action": "Дія",
        "value": "Значення",
        "enter_number": "Введіть число",
        "enter_percent": "Введіть відсоток",
        "enter_value": "Введіть значення",
        "enter_building_name": "Введіть назву будівлі",
        "enter_institution_name": "Введіть назву інституту",

        // Типи вимог
        "defense": "Змінити захист",
        "attack": "Змінити атаку",
        "building_cost": "Змінити вартість будівництва",
        "discontent": "Змінити невдоволення",
        "population_income": "Змінити дохід населення",
        "add_random_culture_population": "Додати населення",
        "prestige": "Змінити престиж",
        "science": "Змінити науку",
        "money": "Змінити гроші",
        "add_oil": "Додати нафту",
        "add_cruiser": "Додати крейсер",
        "add_battleship": "Додати лінкор",
        "add_tank": "Додати танк",
        "add_shock_infantry": "Додати ударну піхоту",
        "add_infantry": "Додати піхоту",
        "army_losses": "Втрати армії",
        "relation_ideology_change": "Змінити відносини з ідеологією",
        "relation_change": "Змінити відносини",
        "diplomacy_lift_sanctions": "Зняти санкції",
        "diplomacy_sanctions": "Накласці санкції",
        "diplomacy_pact": "Укласти пакт",
        "diplomacy_alliance": "Укласти альянс",
        "diplomacy_peace": "Укласти мир",
        "diplomacy_war": "Оголосити війну",
        "resurrect_country": "Відновити країну",
        "annex_country": "Анексувати країну",

        // Reforms page
        "reforms_title": "Реформи",
        "add_reform": "Додати реформу",
        "paste": "Вставити",
        "required_ideology": "Необхідна ідеологія",
        "provinces_amount": "Кількість провінцій",
        "actions": "Дії",

        // Редагування реформи
        "edit_reform": "Редагування реформи",
        "back": "Назад",
        "copy_to_buffer": "Копіювати в буфер",
        "load_for_sync": "Завантажити для синхронізації",
        "new_reform": "Нова реформа",

        // Загальні
        "yes": "Так",
        "no": "Ні",
        "edit": "Редагувати",
        "select_country": "Виберіть країну",
        "select_country_placeholder": "Виберіть країну...",
        "turn_number": "Хід:",

        // Модальні вікна
        "new_country": "Нова країна",
        "create": "Створити",
        "fill_all_fields": "Будь ласка, заповніть усі поля",
        "country_exists": "Країна з таким ID вже існує",
        "relation_params": "Параметри відносин",
        "relation_turn": "Хід початку",
        "relation_duration": "Тривалість",
        "relation_initiator": "Ініціатор",
        "relation_turn_short": "Хід",
        "relation_duration_short": "Тривалість",
        "relation_initiator_short": "Ініціатор",

        // Назви країн
        "country_civilization_13": "Велика Британія",
        "country_civilization_21": "Франція",
        "country_civilization_22": "Ресей Империясы",
        "country_undeveloped_land": "Нерозвинені землі",

        // File upload section
        "drag_file_here_or": "Перетягніть файл сюди або",
        "choose_file": "Виберіть файл",
        "file_preview": "Попередній перегляд файлу",
        "event_id": "ID",
        "event_group": "Група",
        "event_unique_name": "Системна назва",
        "event_title": "Заголовок",
        "event_hide_later": "Приховати пізніше",
        "event_delete_turns": "Видалити через (ходів)",
        "event_description": "Опис події",
        "answer_text": "Текст відповіді",
        "result_description": "Опис результату",
        "auto_select_if_ignored": "Вибирати при ігноруванні",
        "reforms_of": "Реформи",
        "copy_suffix": "копія",
        "function_in_development": "Ця функція знаходиться в розробці",
        "many": "Багато",

        // Event images and icons
        "image_preview": "Попередній перегляд зображення",
        "icon_preview": "Попередній перегляд іконки",
        
        // Main page settings
        "file_parse_error": "Помилка читання файлу",
        "file_access_error": "Помилка доступу до файлу",
        "file_saved": "Файл збережено",
        "file_downloaded": "Файл завантажено",
        "file_update_error": "Помилка оновлення файлу",
        "water_color_update_error": "Помилка оновлення кольору води",

        // Reform colors
        "random_color": "R",

        // Answers
        "answer_1_title": "Відповідь 1",
        "answer_2_title": "Відповідь 2",
        "answer_3_title": "Відповідь 3",

        // Випадаюче меню облікового запису
        "profile": "Профіль",
        "logout": "Вийти",

        // Типи вимог
        "year": "Рік",
        "month": "Місяць",
        "turn": "Хід",
        "land_id": "ID країни",
        "land_name": "Назва країни",
        "near_water": "Поруч з водою",
        "has_pact": "Має пакт",
        "has_sanctions": "Має санкції",
        "has_war": "У стані війни",
        "enemy_near_capital": "Ворог біля столиці",
        "lost_capital": "Втрачена столиця",
        "is_defeated": "Переможена",
        "land_power": "Сила країни",
        "independent_land": "Незалежна країна",
        "no_enemy": "Немає ворогів",
        "random_value": "Випадкове значення",
        "count_of_tasks": "Кількість завдань",
        "num_of_provinces": "Кількість провінцій",
        "tax": "Податок",
        "building_exists": "Будівля існує",
        "political_institution": "Політичний інститут",

        // Дії
        "more": "Більше",
        "equal": "Дорівнює",
        "not_equal": "Не дорівнює",
        "less": "Менше"
    },
    "be": {
        // Галоўная старонка
        "editor": "Рэдактар",
        "countries": "Краіны",
        "events": "Падзеі",
        "save": "Захаваць",
        "drag_file_here": "Перацягніце файл сюды або",
        "choose_file": "Выберыце файл",
        "file_preview": "Папярэдні прагляд файла",
        "changes_not_saved": "Змены не захаваны",

        // Форма налад
        "title": "Назва",
        "id": "ID",
        "last_turn": "Апошні Ход",
        "year": "Год",
        "month": "Месяц",
        "play_after_last_turn": "Гульня Пасля Апошняга Ходу",
        "technology_lvl": "Узровень Тэхналогій",
        "technologies_are_opened": "Адкрыты Усе Тэхналогіі",
        "resources_spawn": "Спаўн Рэсурсаў",
        "difficulty": "Складанасць",
        "bots_behavior": "Паводзіны Ботаў",
        "no_initial_diplomacy": "Без Пачатковай Дыпламатыі",
        "water_color": "Цвет Воды",
        "no_nuclear_weapon": "Без Ядзернай Зброі",
        "sandbox": "Пясочніца",
        "turn": "Ход",
        "player_land": "Страна Ігрока",
        "fog_of_war": "Туман Войны",
        "map_hash": "Хэш Карты",
        "num_of_provinces": "Количество Провинций",
        "min_game_version": "Минимальная Версія Гри",

        // Значэнні выпадальных спісаў
        "easy": "Лёгка",
        "standard": "Стандартна",
        "hard": "Складана",
        "impossible": "Немагчыма",
        "peaceful": "Мірныя",
        "aggressive": "Агрэсіўныя",
        "low": "Мала",
        "few": "Много",
        "enabled": "Так",
        "disabled": "Не",

        // Рэдактар патрабаванняў
        "requirements_editor": "Рэдактар патрабаванняў",
        "bonus_editor": "Рэдактар бонусаў",
        "type": "Тып",
        "subtype": "Падтып",
        "action": "Дзеянне",
        "value": "Значэнне",
        "enter_number": "Увядзіце лік",
        "enter_percent": "Увядзіце працэнт",
        "enter_value": "Увядзіце значэнне",
        "enter_building_name": "Увядзіце назву будынка",
        "enter_institution_name": "Увядзіце назву інстытута",

        // Тыпы патрабаванняў
        "defense": "Змяніць абарону",
        "attack": "Змяніць атаку",
        "building_cost": "Змяніць кошт будаўніцтва",
        "discontent": "Змяніць незадаволенасць",
        "population_income": "Змяніць даход насельніцтва",
        "add_random_culture_population": "Дадаць насельніцтва",
        "prestige": "Змяніць прэстыж",
        "science": "Змяніць навуку",
        "money": "Змяніць грошы",
        "add_oil": "Дадаць нафту",
        "add_cruiser": "Дадаць крэйсер",
        "add_battleship": "Дадаць лінкор",
        "add_tank": "Дадаць танк",
        "add_shock_infantry": "Дадаць ударную пяхоту",
        "add_infantry": "Дадаць пяхоту",
        "army_losses": "Страты войска",
        "relation_ideology_change": "Змяніць адносіны з ідэалогіяй",
        "relation_change": "Змяніць адносіны",
        "diplomacy_lift_sanctions": "Зняць санкцыі",
        "diplomacy_sanctions": "Накласці санкцыі",
        "diplomacy_pact": "Заключыць пакт",
        "diplomacy_alliance": "Заключыць альянс",
        "diplomacy_peace": "Заключыць мір",
        "diplomacy_war": "Аб'явіць вайну",
        "resurrect_country": "Елді қалпына келтіру",
        "annex_country": "Елді қосып алу",

        // Әрекеттер
        "more": "Больш",
        "equal": "Роўна",
        "not_equal": "Не роўна",
        "less": "Менш",

        // Назвы краін
        "country_civilization_13": "Вялікабрытанія",
        "country_civilization_21": "Францыя",
        "country_civilization_22": "Расійская Імперыя",
        "country_undeveloped_land": "Неразвітыя землі"
    },
    "kk": {
        // Басты бет
        "editor": "Редактор",
        "countries": "Елдер",
        "events": "Оқиғалар",
        "save": "Сақтау",
        "drag_file_here": "Файлды осында сүйреңіз немесе",
        "choose_file": "Файлды таңдаңыз",
        "file_preview": "Файлды алдын ала қарау",
        "changes_not_saved": "Өзгерістер сақталмады",

        // Параметрлер формасы
        "title": "Атауы",
        "id": "ID",
        "last_turn": "Соңғы жүріс",
        "year": "Жыл",
        "month": "Ай",
        "play_after_last_turn": "Соңғы жүрістен кейінгі ойын",
        "technology_lvl": "Технология деңгейі",
        "technologies_are_opened": "Барлық технологиялар ашық",
        "resources_spawn": "Ресурстардың пайда болуы",
        "difficulty": "Қиындық",
        "bots_behavior": "Боттардың мінез-құлқы",
        "no_initial_diplomacy": "Бастапқы дипломатиясыз",
        "no_nuclear_weapon": "Ядролық қарусыз",
        "sandbox": "Құмсалғыш",

        // Тізім мәндері
        "easy": "Оңай",
        "standard": "Стандартты",
        "hard": "Қиын",
        "impossible": "Мүмкін емес",
        "peaceful": "Бейбіт",
        "aggressive": "Агрессивті",
        "low": "Аз",
        "many": "Көп",
        "enabled": "Иә",
        "disabled": "Жоқ",

        // Талаптар редакторы
        "requirements_editor": "Талаптар редакторы",
        "bonus_editor": "Бонустар редакторы",
        "type": "Түрі",
        "subtype": "Қосымша түрі",
        "action": "Әрекет",
        "value": "Мән",
        "enter_number": "Санды енгізіңіз",
        "enter_percent": "Пайызды енгізіңіз",
        "enter_value": "Мәнді енгізіңіз",
        "enter_building_name": "Ғимарат атауын енгізіңіз",
        "enter_institution_name": "Мекеме атауын енгізіңіз",

        // Талаптар түрлері
        "defense": "Қорғанысты өзгерту",
        "attack": "Шабуылды өзгерту",
        "building_cost": "Құрылыс құнын өзгерту",
        "discontent": "Наразылықты өзгерту",
        "population_income": "Халық табысын өзгерту",
        "add_random_culture_population": "Халық қосу",
        "prestige": "Беделді өзгерту",
        "science": "Ғылымды өзгерту",
        "money": "Ақшаны өзгерту",
        "add_oil": "Мұнай қосу",
        "add_cruiser": "Крейсер қосу",
        "add_battleship": "Линкор қосу",
        "add_tank": "Танк қосу",
        "add_shock_infantry": "Соққы жаяу әскерін қосу",
        "add_infantry": "Жаяу әскер қосу",
        "army_losses": "Әскери шығындар",
        "relation_ideology_change": "Идеологиямен қарым-қатынасты өзгерту",
        "relation_change": "Қарым-қатынасты өзгерту",
        "diplomacy_lift_sanctions": "Санкцияларды алып тастау",
        "diplomacy_sanctions": "Санкциялар салу",
        "diplomacy_pact": "Пакт жасау",
        "diplomacy_alliance": "Альянс құру",
        "diplomacy_peace": "Бейбітшілік орнату",
        "diplomacy_war": "Соғыс жариялау",
        "resurrect_country": "Елді қалпына келтіру",
        "annex_country": "Елді қосып алу",

        // Әрекеттер
        "more": "Көп",
        "equal": "Тең",
        "not_equal": "Тең емес",
        "less": "Аз",

        // Ел атаулары
        "country_civilization_13": "Ұлыбритания",
        "country_civilization_21": "Франция",
        "country_civilization_22": "Ресей Империясы",
        "country_undeveloped_land": "Дамымаған жерлер"
    }
}; 